/-
Copyright (c) 2024-2026 Trail of Bits. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import RandomSystems.System.Connect
import AbstractCryptography.Specification.Interfaces

/-!
# The converter monoid `Σ` — generators into `Function.End`

A converter has no carrier: it *is* its action, an element of
`Function.End Φ`, and "is a converter" is membership in the submonoid
generated by the named constructions.  Composition closure and the action
laws are thereby definitional — `Function.End`'s multiplication is
composition and its action is application — while every substantive law
is proven per generator and extended by closure induction, consumed from
the abstract layer (`AbstractCryptography.Specification.Interfaces`).

All three generator families are presented, each with its `ActCommute`
base cases and its MR16-§7 grouping receipt consumed from
`orderInvariant_attachedWithin` with no new induction code:

* `relabelAt i t` — query relabelling at one interface of the tagged
  carrier `PDS (P × A) B`: a trivial converter (LiuZhang §3.3.3);
  disjoint-interface relabellings commute by `relabelLaw` functoriality
  plus a disjoint-support function argument.
* `blockAt i` — MauRen16 §3.4's `⊣`: blocks commute unconditionally
  (consecutive blocks merge into the union), and commute with relabelling
  because the block predicate reads only interface tags.
* `attachEngineAt i E` — the interactive family: an engine attached at one
  interface, `PDS.attachEngineLaw` as a monoid element.  Disjoint
  attachments commute by the carrier theorem `attachEngine_comm` —
  MauRen16 §3.3's composition-order-independence axiom, discharged.
-/

namespace RandomSystems

namespace Converter

noncomputable section

open Classical

open AbstractCryptography

open Probability (Distribution)

universe u v w

variable {P : Type u} {A : Type v} {B : Type w}

/-- Query relabelling at one interface: translate the queries placed at
interface `i` by `t`, leave every other interface untouched.  A trivial
converter — no state, no queries of its own — as an element of the
converter monoid `Function.End (PDS (P × A) B)`. -/
def relabelAt (i : P) (t : A → A) : Function.End (PDS (P × A) B) :=
  PDS.relabelLaw (fun p : P × A => if p.1 = i then (i, t p.2) else p) id

/-- Address maps supported on distinct interfaces commute as functions. -/
theorem relabelAt_addr_comm {i j : P} (hij : i ≠ j) (t t' : A → A) :
    ((fun p : P × A => if p.1 = j then (j, t' p.2) else p) ∘
        fun p : P × A => if p.1 = i then (i, t p.2) else p) =
      ((fun p : P × A => if p.1 = i then (i, t p.2) else p) ∘
        fun p : P × A => if p.1 = j then (j, t' p.2) else p) := by
  funext p
  obtain ⟨q, a⟩ := p
  by_cases hqi : q = i
  · subst hqi
    simp [Function.comp, hij]
  · by_cases hqj : q = j
    · subst hqj
      simp [Function.comp, hqi]
    · simp [Function.comp, hqi, hqj]

/-- The order-invariance base case for relabelling: converters that touch
distinct interfaces commute on every resource.  Bottoms out in
`relabelLaw` functoriality and the disjoint-support argument. -/
theorem relabelAt_actCommute {i j : P} (hij : i ≠ j) (t t' : A → A) :
    ActCommute (PDS (P × A) B) (relabelAt (B := B) i t)
      (relabelAt (B := B) j t') := by
  intro S
  show relabelAt i t (relabelAt j t' S) = relabelAt j t' (relabelAt i t S)
  unfold relabelAt
  have h₁ := PDS.relabelLaw_relabelLaw (X := P × A) (Y := B) (X' := P × A)
    (Y' := B) (X'' := P × A) (Y'' := B)
    (fun p : P × A => if p.1 = i then (i, t p.2) else p) id
    (fun p : P × A => if p.1 = j then (j, t' p.2) else p) id S
  have h₂ := PDS.relabelLaw_relabelLaw (X := P × A) (Y := B) (X' := P × A)
    (Y' := B) (X'' := P × A) (Y'' := B)
    (fun p : P × A => if p.1 = j then (j, t' p.2) else p) id
    (fun p : P × A => if p.1 = i then (i, t p.2) else p) id S
  rw [h₁, h₂, relabelAt_addr_comm hij]

/-- The relabelling family satisfies the one axiom the abstract grouping
layer asks of an attachment family. -/
theorem pairwiseOrderInvariant_relabelAt :
    PairwiseOrderInvariant (PDS (P × A) B)
      (relabelAt (P := P) (A := A) (B := B)) :=
  fun _ _ hij t t' => relabelAt_actCommute hij t t'

/-- The first closure receipt: relabelling groups at disjoint interface
sets are order invariant — the closure induction is consumed from the
abstract layer, with no new induction code. -/
example {Z₁ Z₂ : Set P} (h : Disjoint Z₁ Z₂) :
    OrderInvariant (PDS (P × A) B)
      (attachedWithin (relabelAt (P := P) (A := A) (B := B)) Z₁).subtype
      (attachedWithin (relabelAt (P := P) (A := A) (B := B)) Z₂).subtype :=
  orderInvariant_attachedWithin _ pairwiseOrderInvariant_relabelAt h

/-! ## Blocking as a converter -/

/-- Blocking at one interface, as a converter: MauRen16 §3.4's `⊣` at
`{i}`, an element of the converter monoid. -/
def blockAt (i : P) : Function.End (PDS (P × A) B) :=
  PDS.blockLaw {i}

/-- Blocks always commute — consecutive blocks merge into the union, and
unions commute.  No disjointness is needed. -/
theorem blockAt_actCommute (i j : P) :
    ActCommute (PDS (P × A) B) (blockAt (A := A) (B := B) i)
      (blockAt (A := A) (B := B) j) := by
  intro S
  show blockAt i (blockAt j S) = blockAt j (blockAt i S)
  unfold blockAt
  rw [PDS.blockLaw_blockLaw, PDS.blockLaw_blockLaw, Set.union_comm]

/-- The `relabelAt` address map preserves interface tags. -/
theorem relabelAt_addr_fst (j : P) (t : A → A) (p : P × A) :
    ((if p.1 = j then (j, t p.2) else p) : P × A).1 = p.1 := by
  split
  · simp_all
  · rfl

/-- Blocking commutes with relabelling unconditionally: the block predicate
reads only tags, and the relabelling address map preserves them. -/
theorem blockAt_actCommute_relabelAt (i j : P) (t : A → A) :
    ActCommute (PDS (P × A) B) (blockAt (A := A) (B := B) i)
      (relabelAt (B := B) j t) := by
  intro S
  show blockAt i (relabelAt j t S) = relabelAt j t (blockAt i S)
  unfold blockAt relabelAt PDS.blockLaw PDS.relabelLaw
  rw [Distribution.fTransform_fTransform, Distribution.fTransform_fTransform]
  refine congrFun (congrArg _ (funext fun s => ?_)) S
  exact System.block_relabel {i} _ (relabelAt_addr_fst j t) id s

/-! ## Engine attachment as a converter -/

/-- **The third generator family**: attach an engine at one interface of
the tagged carrier — the interactive converter, an element of the
converter monoid. -/
def attachEngineAt (i : P) (E : System.DDS (A ⊕ B) (B ⊕ A)) :
    Function.End (PDS (P × A) B) :=
  PDS.attachEngineLaw i E

/-- The order-invariance base case for attachment — MauRen16 §3.3's axiom,
inherited from the carrier theorem `attachEngine_comm`. -/
theorem attachEngineAt_actCommute {i j : P} (hij : i ≠ j)
    (E F : System.DDS (A ⊕ B) (B ⊕ A)) :
    ActCommute (PDS (P × A) B) (attachEngineAt i E) (attachEngineAt j F) := by
  intro S
  show attachEngineAt i E (attachEngineAt j F S) =
    attachEngineAt j F (attachEngineAt i E S)
  exact PDS.attachEngineLaw_attachEngineLaw hij E F S

/-- The attachment family satisfies the one axiom the abstract grouping
layer asks of an attachment family. -/
theorem pairwiseOrderInvariant_attachEngineAt :
    PairwiseOrderInvariant (PDS (P × A) B)
      (attachEngineAt (P := P) (A := A) (B := B)) :=
  fun _ _ hij E F => attachEngineAt_actCommute hij E F

/-- The closure receipt for the interactive family: engine attachments at
disjoint interface sets are order invariant — the closure induction is
consumed from the abstract layer, with no new induction code. -/
example {Z₁ Z₂ : Set P} (h : Disjoint Z₁ Z₂) :
    OrderInvariant (PDS (P × A) B)
      (attachedWithin (attachEngineAt (P := P) (A := A) (B := B)) Z₁).subtype
      (attachedWithin (attachEngineAt (P := P) (A := A) (B := B)) Z₂).subtype :=
  orderInvariant_attachedWithin _ pairwiseOrderInvariant_attachEngineAt h

/-- Attachment commutes with relabelling at a distinct interface: the
engine's requests carry its own tag, which the relabelling fixes. -/
theorem attachEngineAt_actCommute_relabelAt {i j : P} (hij : i ≠ j)
    (E : System.DDS (A ⊕ B) (B ⊕ A)) (t : A → A) :
    ActCommute (PDS (P × A) B) (attachEngineAt i E)
      (relabelAt (B := B) j t) := by
  intro S
  show attachEngineAt i E (relabelAt j t S) =
    relabelAt j t (attachEngineAt i E S)
  unfold attachEngineAt relabelAt PDS.attachEngineLaw PDS.relabelLaw
  rw [Distribution.fTransform_fTransform, Distribution.fTransform_fTransform]
  refine congrFun (congrArg _ (funext fun s => ?_)) S
  exact System.attachEngine_relabel (relabelAt_addr_fst j t)
    (fun p hpi => by rw [hpi, if_neg hij])

/-- Attachment commutes with blocking at a distinct interface: the
engine's requests carry its own tag, which the block permits. -/
theorem attachEngineAt_actCommute_blockAt {i j : P} (hij : i ≠ j)
    (E : System.DDS (A ⊕ B) (B ⊕ A)) :
    ActCommute (PDS (P × A) B) (attachEngineAt i E)
      (blockAt (A := A) (B := B) j) := by
  intro S
  show attachEngineAt i E (blockAt j S) = blockAt j (attachEngineAt i E S)
  unfold attachEngineAt blockAt PDS.attachEngineLaw PDS.blockLaw
  rw [Distribution.fTransform_fTransform, Distribution.fTransform_fTransform]
  refine congrFun (congrArg _ (funext fun s => ?_)) S
  exact System.attachEngine_block (by simp [hij])

/-! ## The converter monoid -/

/-- **The converter monoid `Σ`** (MauRen16 §3.3): the submonoid of
`Function.End (PDS (P × A) B)` generated by the three families.  "Is a
converter" is membership; `id ∈ Σ` and closure under composition are the
submonoid structure, and every unordered pair of generators at distinct
interfaces commutes by the `ActCommute` base-case matrix above. -/
def monoid (P : Type u) (A : Type v) (B : Type w) :
    Submonoid (Function.End (PDS (P × A) B)) :=
  Submonoid.closure
    ((⋃ i, Set.range (relabelAt (B := B) i)) ∪
      Set.range (blockAt (A := A) (B := B)) ∪
      ⋃ i, Set.range (attachEngineAt (P := P) (A := A) (B := B) i))

theorem relabelAt_mem (i : P) (t : A → A) :
    relabelAt (B := B) i t ∈ monoid P A B :=
  Submonoid.subset_closure
    (Or.inl (Or.inl (Set.mem_iUnion.mpr ⟨i, ⟨t, rfl⟩⟩)))

theorem blockAt_mem (i : P) :
    blockAt (A := A) (B := B) i ∈ monoid P A B :=
  Submonoid.subset_closure (Or.inl (Or.inr ⟨i, rfl⟩))

theorem attachEngineAt_mem (i : P) (E : System.DDS (A ⊕ B) (B ⊕ A)) :
    attachEngineAt i E ∈ monoid P A B :=
  Submonoid.subset_closure (Or.inr (Set.mem_iUnion.mpr ⟨i, ⟨E, rfl⟩⟩))

end

end Converter

end RandomSystems
