/-
Copyright (c) 2026 Trail of Bits. All rights reserved.
Authors: Marc Ilunga, Claude
-/
import AbstractCryptography.Metric.ReductionRelaxation

/-!
# Context-restricted constructions (Jost, *Thesis*, §4.2)

**MR11-DEFERRED (provenance fence, 2026-08-17): MauRen11 constructs
quarantined pending the MR11 reconciliation task.  No MR16-track file may
import this module — enforced by `scripts/ledgerAudit.sh`.  See `LEDGER.md`
PROVENANCE FENCE.**

Chapter 4 (printed pp. 47–53) replaces the universally quantified environment
of the ordinary construction notion by a declared set of admissible contexts.
A context is a pair `(f, P)`: a *filter converter* `f` applied by the honest
party, and an *auxiliary parallel resource* `P`.  Definition 4.2.2:

  `ℛ ⊢[π, 𝒞, ⟨σ_C⟩, ⟨ε_C⟩]→_cr 𝒮  :⟺  ∀ (f,P) ∈ 𝒞 : f[πℛ, P] ⊆ (f[𝒮,P] σ_(f,P))^(ε_(f,P))`

— one simulator and one budget per context (Figure 4.3).

## Contents

* `Context`, `ContextSet`, `Context.real`, `Context.ideal` — Definition 4.2.1.
* `ConstructsRestricted` — Definition 4.2.2.
* `ConstructsAsym`, `Context.ConstructsAsym`, `ConstructsRestrictedAsym` —
  Definitions 2.2.15 and 4.2.3.
* `ContextSet.closure` — Definition 4.2.4.
* `constructsRestrictedAsym_closure_iff` — Proposition 4.2.5.
* `constructsRestrictedAsym_seq_iff`, `constructsRestrictedAsym_par_iff` —
  Theorem 4.2.6.
* `closure_contextId_eq_univ`,
  `constructsAsym_iff_constructsRestrictedAsym_contextId`,
  `constructsRestrictedAsym_iff_forall_constructsAsym` — Proposition 4.2.7.

## Divergences from the printed statements

* "Negligible" (Definitions 2.2.15, 4.2.3) is abstracted to `BudgetClass`.
* The paper's implicit `∥ 1` extensions are written out: Theorem 4.2.6's
  sequential side condition reads `(f ∘ (π₂ ∥ 1), P) ∈ 𝒞̄₁` where the paper
  prints `(f ∘ π₂, P) ∈ 𝒞̄₁`.
* `𝒞̄` is the set generated by Definition 4.2.4's two moves — an outer filter
  and an extra parallel resource.  `ContextSet.mem_closure_paperForm` is the
  printed shape.
* `IsAssociativePar` is carried explicitly by every §4.2 statement.

## Theorem 4.2.6's necessity half is not proved in the source

The soundness half (side condition ⟹ rule) is proved here.  The source's
paragraph headed "For the reverse direction" assumes the rule fails and derives
that some `𝒞₂`-context is not in `𝒞̄₁` — the contrapositive of soundness, not
necessity.  Necessity needs the syntactic closure `𝒞̄₁` to capture every context
*semantically* dominated by `𝒞₁`, isolated here as `ContextSet.ClosureComplete`,
with `ContextSet.dominates_of_mem_closure` and
`ContextSet.mem_closure_iff_dominates`.

## References

* [D. Jost, *Towards Practical and Sound Cryptography from Composable
  Security*, PhD thesis, ETH Zurich][ThesisJost], §2.2 and §4.2.
* [U. Maurer, R. Renner, *Abstract Cryptography*, ICS 2011][MauRen11], §6.
-/

namespace AbstractCryptography

open Pointwise
open scoped ENNReal

variable {Sigma Φ : Type*}

/-! ## Parallel-composition laws used by Chapter 4 -/

/-- Associativity of parallel composition.  Jost writes auxiliary resources as
tuples `[R₁, …, R_n]` and freely regroups them — Definition 4.2.4's `[Q,U] = P`
is read against the real system `f[πℛ, P]`, so `[πℛ, [Q,U]]` has to be the same
resource as `[[πℛ, Q], U]`.

MauRen11 fn. 10 declines to postulate this ("If `‖` is not associative,
appropriate parentheses are required in the expression `R₁‖⋯‖R_d`").  No global
instance is declared: this is an opt-in mixin that every §4.2 statement
carries. -/
class IsAssociativePar (Φ : Type*) [Par Φ] : Prop where
  /-- Regrouping a three-fold parallel composition. -/
  par_assoc (R S T : Φ) : (R ∥ S) ∥ T = R ∥ (S ∥ T)

section ParHelpers

variable [Par Φ]

/-- Specification-level parallel composition is monotone in its left slot. -/
theorem par_mono_left {A A' B : Set Φ} (h : A ⊆ A') : A ∥ B ⊆ A' ∥ B := by
  rintro x hx
  obtain ⟨a, ha, b, hb, rfl⟩ := mem_par_iff.mp hx
  exact par_mem_par (h ha) hb

/-- Specification-level parallel composition is monotone in its right slot. -/
theorem par_mono_right {A B B' : Set Φ} (h : B ⊆ B') : A ∥ B ⊆ A ∥ B' := by
  rintro x hx
  obtain ⟨a, ha, b, hb, rfl⟩ := mem_par_iff.mp hx
  exact par_mem_par ha (h hb)

/-- `IsAssociativePar` lifts from resources to specifications. -/
theorem par_assoc_set [IsAssociativePar Φ] (A B C : Set Φ) :
    (A ∥ B) ∥ C = A ∥ (B ∥ C) := by
  ext x
  constructor
  · intro hx
    obtain ⟨y, hy, c, hc, rfl⟩ := mem_par_iff.mp hx
    obtain ⟨a, ha, b, hb, rfl⟩ := mem_par_iff.mp hy
    exact mem_par_iff.mpr
      ⟨a, ha, b ∥ c, par_mem_par hb hc, (IsAssociativePar.par_assoc a b c).symm⟩
  · intro hx
    obtain ⟨a, ha, y, hy, rfl⟩ := mem_par_iff.mp hx
    obtain ⟨b, hb, c, hc, rfl⟩ := mem_par_iff.mp hy
    exact mem_par_iff.mpr
      ⟨a ∥ b, par_mem_par ha hb, c, hc, IsAssociativePar.par_assoc a b c⟩

/-- A right-neutral resource stays neutral at the specification level.  This is
Jost's `□`, "the neutral resource for which we have `[R,□] = R`" (§4.2.3). -/
theorem par_singleton_neutral_right {u : Φ} (hu : ∀ R : Φ, R ∥ u = R) (A : Set Φ) :
    A ∥ ({u} : Set Φ) = A := by
  ext x
  constructor
  · intro hx
    obtain ⟨a, ha, b, hb, rfl⟩ := mem_par_iff.mp hx
    rw [Set.mem_singleton_iff] at hb
    subst hb
    rwa [hu]
  · intro hx
    exact mem_par_iff.mpr ⟨x, hx, u, rfl, hu x⟩

/-- The specification-level form of `SMulParClass`: a parallel converter pair
acts slotwise on a parallel specification pair. -/
theorem smul_set_par [SMul Sigma Φ] [Par Sigma] [SMulParClass Sigma Φ] (α β : Sigma) (A B : Set Φ) :
    (α ∥ β) • (A ∥ B) = (α • A) ∥ (β • B) := by
  ext x
  constructor
  · rintro ⟨y, hy, rfl⟩
    obtain ⟨a, ha, b, hb, rfl⟩ := mem_par_iff.mp hy
    exact mem_par_iff.mpr
      ⟨α • a, Set.smul_mem_smul_set ha, β • b, Set.smul_mem_smul_set hb,
        (smul_par α β a b).symm⟩
  · intro hx
    obtain ⟨u, hu, v, hv, rfl⟩ := mem_par_iff.mp hx
    obtain ⟨a, ha, rfl⟩ := hu
    obtain ⟨b, hb, rfl⟩ := hv
    exact ⟨a ∥ b, par_mem_par ha hb, smul_par α β a b⟩

/-- The one-sided specialization used throughout §4.2: a protocol extended by
the neutral converter acts on the left slot only.  JM20 Theorem 1.2's `π ∥ 1`,
at the specification level. -/
theorem smul_set_par_one [Monoid Sigma] [MulAction Sigma Φ] [Par Sigma] [SMulParClass Sigma Φ]
    (α : Sigma) (A B : Set Φ) : (α ∥ (1 : Sigma)) • (A ∥ B) = (α • A) ∥ B := by
  rw [smul_set_par, one_smul]

end ParHelpers

/-! ## Definition 4.2.1 — contexts -/

/-- Jost, *Thesis*, §4.2.1, before **Definition 4.2.1**: "we define a context in
which we allow the resource `S` to be used.  A context consists of an auxiliary
parallel resource `P` and some converter `f` applied by the honest party.  We
usually call this converter `f` a *filter* to indicate that its goal is to
restrict the access to the resource `S`."

**Definition 4.2.1**: "A context set `𝒞` is a subset of `Σ × Θ`, where `Σ`
denotes the set of all protocols for the honest parties and `Θ` denotes the set
of all resources."  Here `Σ` is the converter monoid `Sigma` and `Θ` the resource
carrier `Φ`. -/
structure Context (Sigma Φ : Type*) where
  /-- The filter converter applied by the honest party. -/
  filter : Sigma
  /-- The auxiliary parallel resource. -/
  aux : Φ

/-- Definition 4.2.1's `𝒞 ⊆ Σ × Θ`. -/
abbrev ContextSet (Sigma Φ : Type*) : Type _ := Set (Context Sigma Φ)

namespace Context

section Systems

variable [Monoid Sigma] [MulAction Sigma Φ] [Par Φ]

/-- Figure 4.3, left: the real system `f[πℛ, P]` of Definition 4.2.2.  The
protocol acts on the assumed specification only; the filter acts on the whole
composite. -/
def real (c : Context Sigma Φ) (π : Sigma) (R : Set Φ) : Set Φ :=
  c.filter • ((π • R) ∥ ({c.aux} : Set Φ))

/-- Figure 4.3, right: the ideal system `f[𝒮, P]σ` of Definition 4.2.2.  Per
§4.1.3's convention, "whenever a protocol converter `π` is considered, it is
understood to be connected to Alice's interfaces, and whenever a simulator `σ`
is considered, it is understood to be connected to Eve's interfaces", so the
simulator wraps the whole composite `[𝒮, P]` from the other side. -/
def ideal (c : Context Sigma Φ) (σ : Sigma) (S : Set Φ) : Set Φ :=
  c.filter • (σ • (S ∥ ({c.aux} : Set Φ)))

end Systems

end Context

/-! ## Budget classes — the abstraction of "negligible" -/

/-- The closure properties of the negligibility notion that §2.2 and §4.2
consume, packaged as a class of distinguisher-indexed budgets.

Jost, *Thesis*, proof sketch of **Corollary 2.2.16**: "This follows directly
from Corollary 2.2.13 and the closedness properties of the standard efficiency
and negligibility notions.  In particular, for two efficient simulator families
`⟨σ_λ⟩` and `⟨σ'_λ⟩`, their sequential composition is efficient as well.
Moreover, if `⟨ε_λ⟩` is negligible and `⟨π'_λ⟩` and `𝒯 ⊆ Θ_poly` are efficient,
then `⟨(ε_λ)_{π'_λ}⟩` and `⟨(ε_λ)_𝒯⟩` are negligible as well."  Those are
exactly `attachBudget_mem` and `parRightBudget_mem`; `add_mem` is Theorem
2.2.10's `(ℛ^{ε₁})^{ε₂} ⊆ ℛ^{ε₁+ε₂}`, and `zero_mem` is the exact statement.

An information-theoretic reading takes the class of budgets bounded by a fixed
constant; a computational reading takes the negligible families. -/
structure BudgetClass [SMul Sigma Φ] [Par Φ] (D : DistinguisherClass Sigma Φ)
    [D.IsClosedUnderPar] where
  /-- The admitted distinguisher-indexed budgets. -/
  carrier : Set (D.tests → ℝ≥0∞)
  /-- An exact statement is admitted. -/
  zero_mem : (0 : D.tests → ℝ≥0∞) ∈ carrier
  /-- Theorem 2.2.10: accumulated error stays admitted. -/
  add_mem : ∀ {ε₁ ε₂ : D.tests → ℝ≥0∞}, ε₁ ∈ carrier → ε₂ ∈ carrier →
    ε₁ + ε₂ ∈ carrier
  /-- Corollary 2.2.16: `⟨(ε_λ)_{π_λ}⟩` stays admitted (Theorem 2.2.11's
  protocol transform). -/
  attachBudget_mem : ∀ (c : Sigma) {ε : D.tests → ℝ≥0∞}, ε ∈ carrier →
    D.attachBudget c ε ∈ carrier
  /-- Corollary 2.2.16: `⟨(ε_λ)_𝒯⟩` stays admitted (Theorem 2.2.11's parallel
  transform). -/
  parRightBudget_mem : ∀ (T : Set Φ) {ε : D.tests → ℝ≥0∞}, ε ∈ carrier →
    D.parRightBudget T ε ∈ carrier

/-! ## Definitions 2.2.15, 4.2.2 and 4.2.3 — the construction notions -/

section Notions

variable [Monoid Sigma] [MulAction Sigma Φ] [Par Φ]
  {D : DistinguisherClass Sigma Φ} [D.IsClosedUnderPar]

/-- Jost, *Thesis*, **Definition 4.2.2**: "Let `𝒞 ⊆ Σ × Θ` be a given set of
contexts, let `ℛ` and `𝒮` be two specifications, and let `π` be an arbitrary
protocol.  Moreover, let `⟨σ_C⟩_{C∈𝒞}` be simulators for each context, and let
`⟨ε_C⟩_{C∈𝒞}` be functions mapping distinguishers to values in `[0,1]`.  Then,
we define

  `ℛ ⊢[π,⟨σ_C⟩,⟨ε_C⟩,𝒞]→_cr 𝒮 :⟺ ∀(f,P) ∈ 𝒞 : f[πℛ,P] ⊆ (f[𝒮,P]σ_(f,P))^{ε_(f,P)}`,

and say that the protocol `π` `𝒞`-restricted constructs `𝒮` from `ℛ`."

The relaxation is Definition 2.2.9's reduction relaxation — the paper's `ε_C`
maps *distinguishers* to `[0,1]`, so this is `reductionRelaxation`, not a
scalar ball. -/
def ConstructsRestricted (D : DistinguisherClass Sigma Φ) [D.IsClosedUnderPar]
    (π : Sigma) (C : ContextSet Sigma Φ) (σ : Context Sigma Φ → Sigma)
    (ε : Context Sigma Φ → D.tests → ℝ≥0∞) (R S : Set Φ) : Prop :=
  ∀ c ∈ C, c.real π R ⊆ D.reductionRelaxation (ε c) (c.ideal (σ c) S)

/-- Jost, *Thesis*, **Definition 2.2.15**, with negligibility abstracted to a
`BudgetClass` and the asymptotic family index suppressed: "If there exists an
efficient simulator family `⟨σ_λ⟩`, and a negligible family of functions
`⟨ε_λ⟩`, such that `∀λ ∈ ℕ : π_λ(ℛ_λ) ⊆ (σ_λ(𝒮_λ))^{ε_λ}`, we say that the
protocol `π` asymptotically constructs `𝒮` from `ℛ`."

The simulator is drawn from a submonoid `H` — Definition 2.2.14's efficient
converter families. -/
def ConstructsAsym (D : DistinguisherClass Sigma Φ) [D.IsClosedUnderPar]
    (H : Submonoid Sigma) (E : BudgetClass D) (π : Sigma) (R S : Set Φ) : Prop :=
  ∃ σ ∈ H, ∃ ε ∈ E.carrier, R —[π]→ D.reductionRelaxation ε (σ • S)

/-- Definition 4.2.3 at a single context: `f[πℛ,P] ⊆ (f[𝒮,P]σ)^ε` for some
admitted simulator and budget. -/
def Context.ConstructsAsym (c : Context Sigma Φ) (D : DistinguisherClass Sigma Φ)
    [D.IsClosedUnderPar] (H : Submonoid Sigma) (E : BudgetClass D) (π : Sigma)
    (R S : Set Φ) : Prop :=
  ∃ σ ∈ H, ∃ ε ∈ E.carrier, c.real π R ⊆ D.reductionRelaxation ε (c.ideal σ S)

/-- Jost, *Thesis*, **Definition 4.2.3**: "Let `𝒞 ⊆ Σ_poly × Θ_poly` be a given
set of efficient context families … If there exists an efficient simulator
family `⟨σ_{C,λ}⟩` and a negligible family of functions `⟨ε_{C,λ}⟩`, such that

  `∀(f,P) ∈ 𝒞 ∀λ ∈ ℕ : f_λ[π_λ ℛ_λ, P_λ] ⊆ (σ_{(f,P),λ} f_λ[𝒮_λ, P_λ])^{ε_{(f,P),λ}}`,

… we say that the protocol `π` asymptotically `𝒞`-restricted constructs `𝒮`
from `ℛ`."

Definition 4.2.2's simulator and budget *families* become the per-context
existentials; `constructsRestrictedAsym_of_constructsRestricted` is the
bridge. -/
def ConstructsRestrictedAsym (D : DistinguisherClass Sigma Φ) [D.IsClosedUnderPar]
    (H : Submonoid Sigma) (E : BudgetClass D) (π : Sigma) (C : ContextSet Sigma Φ)
    (R S : Set Φ) : Prop :=
  ∀ c ∈ C, c.ConstructsAsym D H E π R S

variable {H : Submonoid Sigma} {E : BudgetClass D} {π : Sigma} {C : ContextSet Sigma Φ}
  {R S : Set Φ}

/-- Definition 4.2.2 refines Definition 4.2.3: exhibited simulator and budget
families that stay inside the admitted classes give the existential notion. -/
theorem constructsRestrictedAsym_of_constructsRestricted
    {σ : Context Sigma Φ → Sigma} {ε : Context Sigma Φ → D.tests → ℝ≥0∞}
    (hσ : ∀ c ∈ C, σ c ∈ H) (hε : ∀ c ∈ C, ε c ∈ E.carrier)
    (h : ConstructsRestricted D π C σ ε R S) :
    ConstructsRestrictedAsym D H E π C R S :=
  fun c hc => ⟨σ c, hσ c hc, ε c, hε c hc, h c hc⟩

/-- The notion is antitone in the context set: demanding more contexts is a
stronger statement. -/
theorem ConstructsRestrictedAsym.mono {C' : ContextSet Sigma Φ} (hC : C ⊆ C')
    (h : ConstructsRestrictedAsym D H E π C' R S) :
    ConstructsRestrictedAsym D H E π C R S :=
  fun c hc => h c (hC hc)

end Notions

/-! ## Definition 4.2.4 — the closure of a context set -/

namespace ContextSet

section Closure

variable [Monoid Sigma] [Par Sigma] [Par Φ]

/-- Jost, *Thesis*, **Definition 4.2.4**: "Let `𝒞 ⊆ Σ × Θ` be a given set of
contexts.  We denote by `𝒞̄ ⊆ Σ × Θ` the following set of contexts:

  `𝒞̄ := {(f,P) ∈ Σ × Θ | ∃(g,Q) ∈ 𝒞 ∃h ∈ Σ ∃U ∈ Θ : h ∘ g = f ∧ [Q,U] = P}`."

Motivated by the preceding paragraph: "Especially, if `S` can be constructed
from `R` within `(f,P)`, so can it within `(f' ∘ f, [P,P'])`.  This is because
`f'` and `P'` can be accounted for in the reduction, or in the case of the
asymptotic notion be simply absorbed into the distinguisher."

Rendered as the set generated by the clause's two moves (header delta 3):
in an algebra where `α ∥ 1 ≠ α` (MauRen11 fn. 23) the printed one-clause set
does not contain `𝒞`.  `mem_closure_paperForm` recovers Definition 4.2.4's
displayed shape. -/
inductive Closure (C : ContextSet Sigma Φ) : Context Sigma Φ → Prop
  /-- Every declared context is admissible. -/
  | base {c : Context Sigma Φ} (hc : c ∈ C) : Closure C c
  /-- Definition 4.2.4's outer filter: `h ∘ g`. -/
  | outerFilter {c : Context Sigma Φ} (h : Sigma) (hc : Closure C c) :
      Closure C ⟨h * c.filter, c.aux⟩
  /-- Definition 4.2.4's extra parallel resource: `[Q,U]`.  The filter carries
  the neutral-converter extension to the new slot. -/
  | parallelResource {c : Context Sigma Φ} (Z : Φ) (hc : Closure C c) :
      Closure C ⟨c.filter ∥ (1 : Sigma), c.aux ∥ Z⟩

/-- Definition 4.2.4's `𝒞̄`, as a set of contexts. -/
def closure (C : ContextSet Sigma Φ) : ContextSet Sigma Φ := {c | Closure C c}

@[simp] theorem mem_closure_iff {C : ContextSet Sigma Φ} {c : Context Sigma Φ} :
    c ∈ closure C ↔ Closure C c := Iff.rfl

/-- Proposition 4.2.5's "the implication `⟸` is trivial, since `𝒞 ⊆ 𝒞̄`". -/
theorem subset_closure (C : ContextSet Sigma Φ) : C ⊆ closure C :=
  fun _ hc => Closure.base hc

/-- Definition 4.2.4's displayed one-step shape: an outer filter `h` composed
with the neutral-slot extension of `g`, and an extra parallel resource `U`. -/
theorem mem_closure_paperForm {C : ContextSet Sigma Φ} {d : Context Sigma Φ}
    (hd : d ∈ C) (h : Sigma) (U : Φ) :
    (⟨h * (d.filter ∥ (1 : Sigma)), d.aux ∥ U⟩ : Context Sigma Φ) ∈ closure C :=
  Closure.outerFilter h (Closure.parallelResource U (Closure.base hd))

theorem closure_mono {C C' : ContextSet Sigma Φ} (h : C ⊆ C') :
    closure C ⊆ closure C' := by
  intro c hc
  induction hc with
  | base hd => exact Closure.base (h hd)
  | outerFilter g _ ih => exact Closure.outerFilter g ih
  | parallelResource Z _ ih => exact Closure.parallelResource Z ih

/-- The closure operator is idempotent — the set-level statement underlying
Proposition 4.2.5's idempotence of the notion. -/
theorem closure_closure (C : ContextSet Sigma Φ) : closure (closure C) = closure C := by
  refine Set.Subset.antisymm (fun c hc => ?_) (subset_closure _)
  induction hc with
  | base hd => exact hd
  | outerFilter g _ ih => exact Closure.outerFilter g ih
  | parallelResource Z _ ih => exact Closure.parallelResource Z ih

end Closure

end ContextSet

/-! ## Proposition 4.2.5 — idempotence under the closure -/

section Idempotence

variable [Monoid Sigma] [MulAction Sigma Φ] [Par Φ] [Par Sigma] [SMulParClass Sigma Φ]
  [IsAssociativePar Φ] {D : DistinguisherClass Sigma Φ} [D.IsClosedUnderPar]
  {H : Submonoid Sigma} {E : BudgetClass D} {π : Sigma} {C : ContextSet Sigma Φ}
  {R S : Set Φ}

omit [Par Sigma] [SMulParClass Sigma Φ] [IsAssociativePar Φ] in
/-- The single-context content of Proposition 4.2.5: a statement in a context
survives an outer filter, at the reduction-transported budget `ε_h`. -/
theorem Context.ConstructsAsym.outerFilter {c : Context Sigma Φ} (h : Sigma)
    (hc : c.ConstructsAsym D H E π R S) :
    (⟨h * c.filter, c.aux⟩ : Context Sigma Φ).ConstructsAsym D H E π R S := by
  obtain ⟨σ, hσ, ε, hε, hsub⟩ := hc
  refine ⟨σ, hσ, D.attachBudget h ε, E.attachBudget_mem h hε, ?_⟩
  show (h * c.filter) • ((π • R) ∥ ({c.aux} : Set Φ)) ⊆ _
  rw [mul_smul]
  calc h • (c.filter • ((π • R) ∥ ({c.aux} : Set Φ)))
      ⊆ h • D.reductionRelaxation ε (c.ideal σ S) := Set.smul_set_mono hsub
    _ ⊆ D.reductionRelaxation (D.attachBudget h ε) (h • c.ideal σ S) :=
        D.smul_reductionRelaxation_subset h ε _
    _ = D.reductionRelaxation (D.attachBudget h ε)
          ((⟨h * c.filter, c.aux⟩ : Context Sigma Φ).ideal σ S) := by
        rw [Context.ideal, Context.ideal, mul_smul]

/-- The single-context content of Proposition 4.2.5: a statement in a context
survives an extra parallel resource, at the reduction-transported budget
`ε_{[Z]}` and the neutral-slot extension of the simulator. -/
theorem Context.ConstructsAsym.parallelResource {c : Context Sigma Φ} (Z : Φ)
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H) (hc : c.ConstructsAsym D H E π R S) :
    (⟨c.filter ∥ (1 : Sigma), c.aux ∥ Z⟩ : Context Sigma Φ).ConstructsAsym D H E π R S := by
  obtain ⟨σ, hσ, ε, hε, hsub⟩ := hc
  refine ⟨σ ∥ (1 : Sigma), hH σ hσ, D.parRightBudget ({Z} : Set Φ) ε,
    E.parRightBudget_mem _ hε, ?_⟩
  have hreal : (⟨c.filter ∥ (1 : Sigma), c.aux ∥ Z⟩ : Context Sigma Φ).real π R
      = (c.real π R) ∥ ({Z} : Set Φ) := by
    rw [Context.real, Context.real, ← singleton_par_singleton, ← par_assoc_set,
      smul_set_par_one]
  have hideal : (⟨c.filter ∥ (1 : Sigma), c.aux ∥ Z⟩ : Context Sigma Φ).ideal (σ ∥ (1 : Sigma)) S
      = (c.ideal σ S) ∥ ({Z} : Set Φ) := by
    rw [Context.ideal, Context.ideal, ← singleton_par_singleton, ← par_assoc_set,
      smul_set_par_one, smul_set_par_one]
  rw [hreal, hideal]
  calc (c.real π R) ∥ ({Z} : Set Φ)
      ⊆ D.reductionRelaxation ε (c.ideal σ S) ∥ ({Z} : Set Φ) := par_mono_left hsub
    _ ⊆ D.reductionRelaxation (D.parRightBudget ({Z} : Set Φ) ε)
          (c.ideal σ S ∥ ({Z} : Set Φ)) :=
        D.reductionRelaxation_par_subset ε _ _

/-- Jost, *Thesis*, **Proposition 4.2.5** (the substantial direction): a
`𝒞`-restricted construction is a `𝒞̄`-restricted construction.

"Let `(f,P) ∈ 𝒞̄` and notice that by Definition 4.2.4 this implies that there
exists `(g,Q) ∈ 𝒞`, `h ∈ Σ`, and `Z ∈ Θ` such that `h ∘ g = f` and `[Q,Z] = P`.
By our assumption, we know that for all `R ∈ ℛ`, there exists a `S ∈ 𝒮` and an
appropriate simulator `σ` such that `g π[R,Q]` is computationally
indistinguishable from `g[S,Q]σ` … Thus, if we add the additional filter `h`
and resource `Z`, they remain indistinguishable."

The budget bookkeeping the paper leaves to "accounted for in the reduction" is
Theorem 2.2.11's two transforms, `attachBudget` and `parRightBudget`; `hH` is
the closure of the simulator class under the neutral-slot extension. -/
theorem constructsRestrictedAsym_closure
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H)
    (h : ConstructsRestrictedAsym D H E π C R S) :
    ConstructsRestrictedAsym D H E π (ContextSet.closure C) R S := by
  intro c hc
  induction hc with
  | base hd => exact h _ hd
  | outerFilter g _ ih => exact ih.outerFilter g
  | parallelResource Z _ ih => exact ih.parallelResource Z hH

/-- Jost, *Thesis*, **Proposition 4.2.5**: "The context-restricted construction
notion is idempotent under the closure of the context set … `ℛ ⊢[π,𝒞]→_cr-asym 𝒮
⟺ ℛ ⊢[π,𝒞̄]→_cr-asym 𝒮`." -/
theorem constructsRestrictedAsym_closure_iff (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H) :
    ConstructsRestrictedAsym D H E π C R S ↔
      ConstructsRestrictedAsym D H E π (ContextSet.closure C) R S :=
  ⟨constructsRestrictedAsym_closure hH,
    ConstructsRestrictedAsym.mono (ContextSet.subset_closure C)⟩

end Idempotence

/-! ## Semantic domination and the premise Theorem 4.2.6 needs -/

namespace ContextSet

section Domination

variable [Monoid Sigma] [MulAction Sigma Φ] [Par Φ] [Par Sigma] [SMulParClass Sigma Φ]
  [IsAssociativePar Φ] {D : DistinguisherClass Sigma Φ} [D.IsClosedUnderPar]
  {H : Submonoid Sigma} {E : BudgetClass D} {π : Sigma}

/-- `c` is *dominated* by `𝒞` at `π` when every `𝒞`-restricted construction
statement with protocol `π` also holds in the single context `c` — the semantic
content that Definition 4.2.4's syntactic closure is meant to compute. -/
def Dominates (C : ContextSet Sigma Φ) (D : DistinguisherClass Sigma Φ)
    [D.IsClosedUnderPar] (H : Submonoid Sigma) (E : BudgetClass D) (π : Sigma)
    (c : Context Sigma Φ) : Prop :=
  ∀ R S : Set Φ, ConstructsRestrictedAsym D H E π C R S →
    c.ConstructsAsym D H E π R S

/-- Proposition 4.2.5, read semantically: the closure only ever adds dominated
contexts.  This direction is unconditional. -/
theorem dominates_of_mem_closure {C : ContextSet Sigma Φ}
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H) {c : Context Sigma Φ} (hc : c ∈ closure C) :
    Dominates C D H E π c :=
  fun _ _ h => constructsRestrictedAsym_closure hH h c hc

/-- Completeness of Definition 4.2.4's syntactic closure: a context that no
`𝒞`-restricted statement can distinguish already lies in `𝒞̄`.

`dominates_of_mem_closure` proves the closure sound; Theorem 4.2.6's necessity
half additionally needs it complete, and the thesis does not prove that (see
this module's header).  A necessity proof must produce a separating pair of
specifications for every context outside `𝒞̄₁`, a richness property of the
carrier and the context set. -/
def ClosureComplete (C : ContextSet Sigma Φ) (D : DistinguisherClass Sigma Φ)
    [D.IsClosedUnderPar] (H : Submonoid Sigma) (E : BudgetClass D) (π : Sigma) : Prop :=
  ∀ c : Context Sigma Φ, Dominates C D H E π c → c ∈ closure C

/-- Under closure-completeness, membership in Definition 4.2.4's `𝒞̄` *is*
semantic domination. -/
theorem mem_closure_iff_dominates {C : ContextSet Sigma Φ}
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H) (hcomplete : ClosureComplete C D H E π)
    {c : Context Sigma Φ} :
    c ∈ closure C ↔ Dominates C D H E π c :=
  ⟨dominates_of_mem_closure hH, hcomplete c⟩

end Domination

end ContextSet

/-! ## Theorem 4.2.6 — the composition rules -/

section Composition

variable [Monoid Sigma] [MulAction Sigma Φ] [Par Φ] [Par Sigma] [SMulParClass Sigma Φ]
  [IsAssociativePar Φ] {D : DistinguisherClass Sigma Φ} [D.IsClosedUnderPar]
  {H : Submonoid Sigma} {E : BudgetClass D}

/-! ### The trivial construction statements used to instantiate the rules -/

omit [Par Sigma] [SMulParClass Sigma Φ] [IsAssociativePar Φ] in
/-- A protocol always `𝒞`-restricted constructs its own image, exactly and with
the neutral simulator. -/
theorem constructsRestrictedAsym_smul_self (π : Sigma) (C : ContextSet Sigma Φ)
    (R : Set Φ) : ConstructsRestrictedAsym D H E π C R (π • R) := by
  refine fun c _ => ⟨1, one_mem H, 0, E.zero_mem, ?_⟩
  have : c.ideal 1 (π • R) = c.real π R := by
    rw [Context.ideal, Context.real, one_smul]
  rw [this]
  exact (D.reductionRelaxation 0).le_toFun _

/-! ### Sequential composition -/

section Sequential

variable {π₁ π₂ : Sigma} {C₁ C₂ : ContextSet Sigma Φ}

/-- Theorem 4.2.6's sequential rule, the direction the source proves: the side
condition is sufficient.

`hcentral` is §4.1.3's interface separation ("whenever a protocol converter `π`
is considered, it is understood to be connected to Alice's interfaces, and
whenever a simulator `σ` is considered, it is understood to be connected to
Eve's interfaces"), abstracted to: a simulator commutes with every converter.
The resulting budget is Corollary 2.2.13.1's `ε'_σ + ε_{π'}`. -/
theorem constructsRestrictedAsym_seq
    (hcentral : ∀ (m : Sigma), ∀ σ ∈ H, Commute m σ)
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H)
    (hcond : ∀ c ∈ C₂,
      (⟨c.filter * (π₂ ∥ (1 : Sigma)), c.aux⟩ : Context Sigma Φ) ∈ ContextSet.closure C₁)
    {R S T : Set Φ}
    (h₁ : ConstructsRestrictedAsym D H E π₁ C₁ R S)
    (h₂ : ConstructsRestrictedAsym D H E π₂ C₂ S T) :
    ConstructsRestrictedAsym D H E (π₂ * π₁) C₂ R T := by
  intro c hc
  obtain ⟨σ₁, hσ₁, ε₁, hε₁, hA⟩ :=
    constructsRestrictedAsym_closure hH h₁ _ (hcond c hc)
  obtain ⟨σ₂, hσ₂, ε₂, hε₂, hB⟩ := h₂ c hc
  refine ⟨σ₁ * σ₂, mul_mem hσ₁ hσ₂, D.attachBudget σ₁ ε₂ + ε₁,
    E.add_mem (E.attachBudget_mem σ₁ hε₂) hε₁, ?_⟩
  -- §4.1.3's interface separation, in the form the algebra consumes.
  have hcomm : ∀ (m : Sigma) (X : Set Φ), m • (σ₁ • X) = σ₁ • (m • X) := by
    intro m X
    rw [← mul_smul, (hcentral m σ₁ hσ₁).eq, mul_smul]
  -- The real system of the composed statement is the real system of the
  -- extended context `(f ∘ (π₂ ∥ 1), P)`.
  have hreal : c.real (π₂ * π₁) R
      = (⟨c.filter * (π₂ ∥ (1 : Sigma)), c.aux⟩ : Context Sigma Φ).real π₁ R := by
    show c.filter • (((π₂ * π₁) • R) ∥ ({c.aux} : Set Φ))
        = (c.filter * (π₂ ∥ (1 : Sigma))) • ((π₁ • R) ∥ ({c.aux} : Set Φ))
    rw [mul_smul, mul_smul, smul_set_par_one]
  -- The ideal system of the extended context is the real system of the second
  -- leg, wrapped in the first leg's simulator.
  have hmid : (⟨c.filter * (π₂ ∥ (1 : Sigma)), c.aux⟩ : Context Sigma Φ).ideal σ₁ S
      = σ₁ • c.real π₂ S := by
    show (c.filter * (π₂ ∥ (1 : Sigma))) • (σ₁ • (S ∥ ({c.aux} : Set Φ)))
        = σ₁ • (c.filter • ((π₂ • S) ∥ ({c.aux} : Set Φ)))
    rw [mul_smul, hcomm, smul_set_par_one, hcomm]
  have hfinal : σ₁ • c.ideal σ₂ T = c.ideal (σ₁ * σ₂) T := by
    show σ₁ • (c.filter • (σ₂ • (T ∥ ({c.aux} : Set Φ))))
        = c.filter • ((σ₁ * σ₂) • (T ∥ ({c.aux} : Set Φ)))
    rw [← hcomm, ← mul_smul σ₁ σ₂]
  rw [hreal]
  refine hA.trans ?_
  rw [hmid]
  calc D.reductionRelaxation ε₁ (σ₁ • c.real π₂ S)
      ⊆ D.reductionRelaxation ε₁
          (σ₁ • D.reductionRelaxation ε₂ (c.ideal σ₂ T)) :=
        (D.reductionRelaxation ε₁).mono (Set.smul_set_mono hB)
    _ ⊆ D.reductionRelaxation ε₁
          (D.reductionRelaxation (D.attachBudget σ₁ ε₂) (σ₁ • c.ideal σ₂ T)) :=
        (D.reductionRelaxation ε₁).mono
          (D.smul_reductionRelaxation_subset σ₁ ε₂ _)
    _ ⊆ D.reductionRelaxation (D.attachBudget σ₁ ε₂ + ε₁) (σ₁ • c.ideal σ₂ T) :=
        D.reductionRelaxation_reductionRelaxation_subset _
    _ = D.reductionRelaxation (D.attachBudget σ₁ ε₂ + ε₁) (c.ideal (σ₁ * σ₂) T) := by
        rw [hfinal]

/-- Jost, *Thesis*, **Theorem 4.2.6**, sequential rule, as an `iff` on the whole
derivation rule:

  "`ℛ ⊢[π₁,𝒞₁]→ 𝒮 ∧ 𝒮 ⊢[π₂,𝒞₂]→ 𝒯 ⟹ ℛ ⊢[π₂∘π₁,𝒞₂]→ 𝒯`, iff for all
  `(f,P) ∈ 𝒞₂` it holds that `(f ∘ π₂, P) ∈ 𝒞̄₁`."

Explicit here, where the source leaves it implicit:

* `π₂` is a protocol for `𝒮` alone, so inside the context it acts on the
  assumed slot only; the abstract model writes that extension `π₂ ∥ 1` (header
  delta 2).
* The rule is quantified over all `ℛ`, `𝒮`, `𝒯`, since the side condition does
  not mention them.
* The necessity half consumes `ContextSet.ClosureComplete`. -/
theorem constructsRestrictedAsym_seq_iff
    (hcentral : ∀ (m : Sigma), ∀ σ ∈ H, Commute m σ)
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H)
    (hcomplete : ContextSet.ClosureComplete C₁ D H E π₁) :
    (∀ R S T : Set Φ,
        ConstructsRestrictedAsym D H E π₁ C₁ R S →
        ConstructsRestrictedAsym D H E π₂ C₂ S T →
        ConstructsRestrictedAsym D H E (π₂ * π₁) C₂ R T) ↔
      ∀ c ∈ C₂,
        (⟨c.filter * (π₂ ∥ (1 : Sigma)), c.aux⟩ : Context Sigma Φ) ∈
          ContextSet.closure C₁ := by
  constructor
  · intro hrule c hc
    refine hcomplete _ (fun R S h₁ => ?_)
    obtain ⟨σ, hσ, ε, hε, hsub⟩ :=
      hrule R S (π₂ • S) h₁ (constructsRestrictedAsym_smul_self π₂ C₂ S) c hc
    refine ⟨σ, hσ, ε, hε, ?_⟩
    have hcomm : ∀ (m : Sigma) (X : Set Φ), m • (σ • X) = σ • (m • X) := by
      intro m X
      rw [← mul_smul, (hcentral m σ hσ).eq, mul_smul]
    have hreal : c.real (π₂ * π₁) R
        = (⟨c.filter * (π₂ ∥ (1 : Sigma)), c.aux⟩ : Context Sigma Φ).real π₁ R := by
      show c.filter • (((π₂ * π₁) • R) ∥ ({c.aux} : Set Φ))
          = (c.filter * (π₂ ∥ (1 : Sigma))) • ((π₁ • R) ∥ ({c.aux} : Set Φ))
      rw [mul_smul, mul_smul, smul_set_par_one]
    have hideal : c.ideal σ (π₂ • S)
        = (⟨c.filter * (π₂ ∥ (1 : Sigma)), c.aux⟩ : Context Sigma Φ).ideal σ S := by
      show c.filter • (σ • ((π₂ • S) ∥ ({c.aux} : Set Φ)))
          = (c.filter * (π₂ ∥ (1 : Sigma))) • (σ • (S ∥ ({c.aux} : Set Φ)))
      rw [mul_smul, hcomm (π₂ ∥ (1 : Sigma)), smul_set_par_one]
    rw [← hreal, ← hideal]
    exact hsub
  · intro hcond R S T h₁ h₂
    exact constructsRestrictedAsym_seq hcentral hH hcond h₁ h₂

end Sequential

/-! ### Parallel composition -/

section Parallel

variable {π₁ : Sigma} {C₁ C₂ : ContextSet Sigma Φ}

/-- Theorem 4.2.6's parallel rule, the direction the source proves.

"In short, the parallel composition property is just associativity: The
resource `U` can be seen as both part of the context … or part of the real and
ideal resources." -/
theorem constructsRestrictedAsym_par (U : Φ)
    (hcond : ∀ c ∈ C₂,
      (⟨c.filter, U ∥ c.aux⟩ : Context Sigma Φ) ∈ ContextSet.closure C₁)
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H) {R S : Set Φ}
    (h : ConstructsRestrictedAsym D H E π₁ C₁ R S) :
    ConstructsRestrictedAsym D H E (π₁ ∥ (1 : Sigma)) C₂
      (R ∥ ({U} : Set Φ)) (S ∥ ({U} : Set Φ)) := by
  intro c hc
  obtain ⟨σ, hσ, ε, hε, hsub⟩ :=
    constructsRestrictedAsym_closure hH h _ (hcond c hc)
  refine ⟨σ, hσ, ε, hε, ?_⟩
  have hreal : c.real (π₁ ∥ (1 : Sigma)) (R ∥ ({U} : Set Φ))
      = (⟨c.filter, U ∥ c.aux⟩ : Context Sigma Φ).real π₁ R := by
    rw [Context.real, Context.real, smul_set_par_one, ← singleton_par_singleton,
      par_assoc_set]
  have hideal : c.ideal σ (S ∥ ({U} : Set Φ))
      = (⟨c.filter, U ∥ c.aux⟩ : Context Sigma Φ).ideal σ S := by
    rw [Context.ideal, Context.ideal, ← singleton_par_singleton, par_assoc_set]
  rw [hreal, hideal]
  exact hsub

/-- Jost, *Thesis*, **Theorem 4.2.6**, parallel rule, as an `iff` on the whole
derivation rule:

  "`ℛ ⊢[π₁,𝒞₁]→ 𝒮 ⟹ [ℛ,𝒰] ⊢[π₁,𝒞₂]→ [𝒮,𝒰]`, iff for all `(f,P) ∈ 𝒞₂` it
  holds that `(f, [𝒰,P]) ⊆ 𝒞̄₁`."

Explicit here, where the source leaves it implicit:

* `π₁` is a protocol for `ℛ` alone, so on `[ℛ,𝒰]` it is `π₁ ∥ 1` (header delta
  2, and JM20 Theorem 1.2's own convention).
* **`𝒰` is a single resource here, where the source writes a specification.**
  The printed side condition uses `⊆` because `(f,[𝒰,P])` is the *set*
  `{(f,[U,P]) | U ∈ 𝒰}`; but Definition 4.2.2 grants one simulator per context,
  so a non-singleton `𝒰` would need a simulator uniform over `𝒰`.  A single
  auxiliary resource is what Figure 4.3's `U` box and §4.2.4's application
  (`[HK,DH]`, with `DH` one resource) use.
* The necessity half consumes `ContextSet.ClosureComplete`, as in the
  sequential rule. -/
theorem constructsRestrictedAsym_par_iff (U : Φ)
    (hH : ∀ σ ∈ H, σ ∥ (1 : Sigma) ∈ H)
    (hcomplete : ContextSet.ClosureComplete C₁ D H E π₁) :
    (∀ R S : Set Φ,
        ConstructsRestrictedAsym D H E π₁ C₁ R S →
        ConstructsRestrictedAsym D H E (π₁ ∥ (1 : Sigma)) C₂
          (R ∥ ({U} : Set Φ)) (S ∥ ({U} : Set Φ))) ↔
      ∀ c ∈ C₂,
        (⟨c.filter, U ∥ c.aux⟩ : Context Sigma Φ) ∈ ContextSet.closure C₁ := by
  constructor
  · intro hrule c hc
    refine hcomplete _ (fun R S h => ?_)
    obtain ⟨σ, hσ, ε, hε, hsub⟩ := hrule R S h c hc
    refine ⟨σ, hσ, ε, hε, ?_⟩
    have hreal : c.real (π₁ ∥ (1 : Sigma)) (R ∥ ({U} : Set Φ))
        = (⟨c.filter, U ∥ c.aux⟩ : Context Sigma Φ).real π₁ R := by
      rw [Context.real, Context.real, smul_set_par_one, ← singleton_par_singleton,
        par_assoc_set]
    have hideal : c.ideal σ (S ∥ ({U} : Set Φ))
        = (⟨c.filter, U ∥ c.aux⟩ : Context Sigma Φ).ideal σ S := by
      rw [Context.ideal, Context.ideal, ← singleton_par_singleton, par_assoc_set]
    rw [← hreal, ← hideal]
    exact hsub
  · intro hcond R S h
    exact constructsRestrictedAsym_par U hcond hH h

end Parallel

end Composition

/-! ## Proposition 4.2.7 — the relation to regular constructions -/

section Regular

variable [Monoid Sigma] [MulAction Sigma Φ] [Par Φ] [Par Sigma] [SMulParClass Sigma Φ]
  {D : DistinguisherClass Sigma Φ} [D.IsClosedUnderPar]
  {H : Submonoid Sigma} {E : BudgetClass D}

/-- Jost, *Thesis*, §4.2.3: "`𝒞_id := {(id, □)}`", where "`id` denotes the
identity protocol for which we have `id R = R`, and … `□` denotes the neutral
resource for which we have `[R,□] = R`". -/
def contextId (u : Φ) : ContextSet Sigma Φ := {⟨1, u⟩}

omit [MulAction Sigma Φ] [SMulParClass Sigma Φ] in
/-- Jost, *Thesis*, §4.2.3: "`𝒞̄_id = Σ × Θ`, i.e., the closure equals the set
of all resources and converters."

`hone` is the neutral-element dressing `1 ∥ 1 = 1`, far weaker than the
`α ∥ 1 = α` that MauRen11 fn. 23 denies.  `hleft` is the left half of `□`'s
neutrality, which the paper's `[Q,U] = P` instance at `Q = □` uses. -/
theorem closure_contextId_eq_univ {u : Φ} (hone : ((1 : Sigma) ∥ (1 : Sigma)) = 1)
    (hleft : ∀ R : Φ, u ∥ R = R) :
    ContextSet.closure (contextId (Sigma := Sigma) u) = Set.univ := by
  refine Set.eq_univ_of_forall (fun c => ?_)
  have hbase : ContextSet.Closure (contextId (Sigma := Sigma) u) ⟨1, u⟩ :=
    ContextSet.Closure.base rfl
  have hstep := ContextSet.Closure.parallelResource c.aux hbase
  rw [hone, hleft] at hstep
  have hstep2 := ContextSet.Closure.outerFilter c.filter hstep
  rw [mul_one] at hstep2
  exact hstep2

omit [Par Sigma] [SMulParClass Sigma Φ] in
/-- Jost, *Thesis*, **Proposition 4.2.7**, first equivalence: "`ℛ ⊢[π]→_asympt 𝒮
⟺ ℛ ⊢[π,𝒞_id]→_cr-asym 𝒮`" — the ordinary simulation-based notion is the
special case of the context-restricted one at `𝒞_id = {(id,□)}`.

"This follows directly from Definitions 2.2.15 and 4.2.3, and the definitions
of the identity protocol `id` and the neutral resource `□`, respectively." -/
theorem constructsAsym_iff_constructsRestrictedAsym_contextId {u : Φ}
    (hright : ∀ R : Φ, R ∥ u = R) {π : Sigma} {R S : Set Φ} :
    ConstructsAsym D H E π R S ↔
      ConstructsRestrictedAsym D H E π (contextId (Sigma := Sigma) u) R S := by
  have hreal : (⟨1, u⟩ : Context Sigma Φ).real π R = π • R := by
    rw [Context.real, one_smul, par_singleton_neutral_right hright]
  have hideal : ∀ σ : Sigma, (⟨1, u⟩ : Context Sigma Φ).ideal σ S = σ • S := by
    intro σ
    rw [Context.ideal, one_smul, par_singleton_neutral_right hright]
  constructor
  · rintro ⟨σ, hσ, ε, hε, hsub⟩ c hc
    have hc' : c = (⟨1, u⟩ : Context Sigma Φ) := hc
    subst hc'
    exact ⟨σ, hσ, ε, hε, by rw [hreal, hideal]; exact hsub⟩
  · intro h
    obtain ⟨σ, hσ, ε, hε, hsub⟩ := h ⟨1, u⟩ rfl
    rw [hreal, hideal] at hsub
    exact ⟨σ, hσ, ε, hε, hsub⟩

/-- Jost, *Thesis*, **Proposition 4.2.7**, second equivalence: "`ℛ ⊢[π,𝒞]→_cr-asym
𝒮 ⟺ ∀(f,P) ∈ 𝒞 : [ℛ,P] ⊢[f∘π]→_asympt f[𝒮,P]`" — conversely, a
context-restricted construction is exactly a family of ordinary construction
statements with the context folded into the assumed resource and the protocol.

The protocol of the folded statement is `f ∘ (π ∥ 1)`: `π` still applies to the
assumed specification only.  `hcentral` is §4.1.3's interface separation, used
to move the simulator across the filter. -/
theorem constructsRestrictedAsym_iff_forall_constructsAsym
    (hcentral : ∀ (m : Sigma), ∀ σ ∈ H, Commute m σ)
    {π : Sigma} {C : ContextSet Sigma Φ} {R S : Set Φ} :
    ConstructsRestrictedAsym D H E π C R S ↔
      ∀ c ∈ C, ConstructsAsym D H E (c.filter * (π ∥ (1 : Sigma)))
        (R ∥ ({c.aux} : Set Φ)) (c.filter • (S ∥ ({c.aux} : Set Φ))) := by
  have key : ∀ (c : Context Sigma Φ) (σ : Sigma), σ ∈ H →
      (c.filter * (π ∥ (1 : Sigma))) • (R ∥ ({c.aux} : Set Φ)) = c.real π R ∧
      σ • (c.filter • (S ∥ ({c.aux} : Set Φ))) = c.ideal σ S := by
    intro c σ hσ
    refine ⟨?_, ?_⟩
    · rw [Context.real, mul_smul, smul_set_par_one]
    · rw [Context.ideal, ← mul_smul, ← mul_smul, (hcentral _ σ hσ).eq]
  constructor
  · intro h c hc
    obtain ⟨σ, hσ, ε, hε, hsub⟩ := h c hc
    obtain ⟨hr, hi⟩ := key c σ hσ
    exact ⟨σ, hσ, ε, hε, by rw [constructs_iff, hr, hi]; exact hsub⟩
  · intro h c hc
    obtain ⟨σ, hσ, ε, hε, hsub⟩ := h c hc
    obtain ⟨hr, hi⟩ := key c σ hσ
    rw [constructs_iff, hr, hi] at hsub
    exact ⟨σ, hσ, ε, hε, hsub⟩

end Regular

end AbstractCryptography
