/-
Copyright (c) 2024-2026 Trail of Bits. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import RandomSystems.System.Phi
import RandomSystems.Converter.ConverterImpl
import AbstractCryptography.Specification.Interfaces

/-!
# `connect` on Φ

A converter enters as what it is — a system with a sum signature
`E : DDS (U ⊕ Y) (V ⊕ X)`, its inner and outer interfaces as its own
alphabets (CR18 Def 3.8) — and is attached to a *bare* resource `R : Φ` by
the proven interpreter.  The lift of `E` to the universal alphabet is an
authored implementation (`liftImpl`): consult `E` on the decoded history,
include its requests, decode the replies; a foreign reply is out of
domain.  The generic round theorem `ConverterImpl.serve_step` therefore
covers every attachment — the interpreter is never unfolded against a
lifted converter.

The result is re-included into Φ, so `connectPhi E : Φ → Φ` — the
endomorphism family the converter monoid Σ is generated by.
-/

namespace RandomSystems

namespace System

noncomputable section

open Classical

universe u

variable {U Y V X : Type u}

/-- The lift of a converter to the universal alphabet, as an
implementation: the state is `E`'s decoded history; a query is passed to
`E` and its request included; a reply is decoded at `Y` and passed to
`E` — a foreign reply is out of domain. -/
def liftImpl (E : DDS (U ⊕ Y) (V ⊕ X)) :
    ConverterImpl (List (U ⊕ Y)) U Uni.{u} V Uni.{u} where
  init := []
  onQuery := fun s u => (E.1 (s ++ [Sum.inl u])).map fun out =>
    (s ++ [Sum.inl u], Sum.map id (encode X) out)
  onReply := fun s q => (decode Y q).bind fun y =>
    (E.1 (s ++ [Sum.inr y])).map fun out =>
      (s ++ [Sum.inr y], Sum.map id (encode X) out)

/-- The lifted converter: the implementation's engine. -/
def lift (E : DDS (U ⊕ Y) (V ⊕ X)) : DDS (U ⊕ Uni.{u}) (V ⊕ Uni.{u}) :=
  (liftImpl E).engine

/-- **`connect` on Φ**, deterministic level: attach the lifted converter
to the bare resource, and re-include the constructed `(U, V)`-system. -/
def connectPhi (E : DDS (U ⊕ Y) (V ⊕ X))
    (R : DDS Uni.{u} Uni.{u}) : DDS Uni.{u} Uni.{u} :=
  ofTyped (connect (lift E) R)

@[simp] theorem lift_engine (E : DDS (U ⊕ Y) (V ⊕ X)) :
    (liftImpl E).engine = lift E :=
  rfl

/-! ### Transparency of the inclusion

Interpreting a lifted converter against an included resource is
interpreting the converter against the typed resource: the inclusion
round trip is invisible to attachment.  The identity law below is the
special case of a relay converter. -/

section Transparency

/-- The event map of the lift: queries pass, replies are included. -/
abbrev liftEvent (Y : Type u) : (U ⊕ Y) → (U ⊕ Uni.{u}) :=
  Sum.map id (encode Y)

/-- A prefix of a mapped history is a mapped prefix. -/
theorem prefix_map_liftEvent {Y : Type u} :
    ∀ {he : List (U ⊕ Y)} {l' : List (U ⊕ Uni.{u})},
      l' <+: he.map (liftEvent Y) →
      ∃ h₀ : List (U ⊕ Y), h₀ <+: he ∧ l' = h₀.map (liftEvent Y) := by
  intro he
  induction he with
  | nil =>
      intro l' h
      exact ⟨[], List.prefix_refl _, List.prefix_nil.mp h⟩
  | cons e t ih =>
      intro l' h
      cases l' with
      | nil => exact ⟨[], List.nil_prefix, rfl⟩
      | cons e' l'' =>
          rw [List.map_cons, List.cons_prefix_cons] at h
          obtain ⟨rfl, h'⟩ := h
          obtain ⟨h₀, hpre, rfl⟩ := ih h'
          exact ⟨e :: h₀, List.cons_prefix_cons.mpr ⟨rfl, hpre⟩, rfl⟩

/-- A reply included at `Y` decodes back for the lifted converter. -/
theorem liftImpl_onReply_encode (E : DDS (U ⊕ Y) (V ⊕ X))
    (s : List (U ⊕ Y)) (y : Y) :
    (liftImpl E).onReply s (encode Y y) =
      (E.1 (s ++ [Sum.inr y])).map fun out =>
        (s ++ [Sum.inr y], Sum.map id (encode X) out) := by
  show ((decode Y (encode Y y)).bind fun y' =>
    (E.1 (s ++ [Sum.inr y'])).map fun out =>
      (s ++ [Sum.inr y'], Sum.map id (encode X) out)) = _
  rw [decode_encode, Part.bind_some]

/-- One step of the lift on a mapped event, from a defined state. -/
theorem liftImpl_step_map (E : DDS (U ⊕ Y) (V ⊕ X))
    (s : List (U ⊕ Y)) (e : U ⊕ Y) :
    (liftImpl E).step s (liftEvent Y e) =
      (E.1 (s ++ [e])).map fun out =>
        (s ++ [e], Sum.map id (encode X) out) := by
  cases e with
  | inl u => rfl
  | inr y => exact liftImpl_onReply_encode E s y

/-- The lift's state on a mapped history is the typed history itself. -/
theorem state_lift_map (E : DDS (U ⊕ Y) (V ⊕ X)) :
    ∀ (he : List (U ⊕ Y)), (he = [] ∨ he ∈ dom E) →
      (liftImpl E).state (he.map (liftEvent Y)) = Part.some he := by
  intro he
  induction he using List.reverseRecOn with
  | nil => exact fun _ => rfl
  | append_singleton he e ih =>
      intro hd
      have hd' : he ++ [e] ∈ dom E := by
        rcases hd with hd | hd
        · exact absurd hd (by simp)
        · exact hd
      have hpre : he = [] ∨ he ∈ dom E := by
        rcases List.eq_nil_or_concat he with rfl | ⟨h₀, e₀, rfl⟩
        · exact Or.inl rfl
        · exact Or.inr (prefix_closed E (List.prefix_append _ _)
            (by simp) hd')
      rw [List.map_append, List.map_cons, List.map_nil,
        ConverterImpl.state_append, ih hpre, Part.bind_some]
      show ((liftImpl E).step he (liftEvent Y e)).map Prod.fst = _
      rw [liftImpl_step_map]
      refine Part.eq_some_iff.mpr ?_
      refine (Part.mem_map_iff _).mpr ?_
      refine ⟨(he ++ [e], Sum.map id (encode X) (output E (he ++ [e]) hd')),
        ?_, rfl⟩
      exact (Part.mem_map_iff _).mpr ⟨output E (he ++ [e]) hd',
        Part.get_mem hd', rfl⟩

/-- Included coherence: a typed history in the converter's domain maps to
a coherent lifted history. -/
theorem mem_dom_lift_map (E : DDS (U ⊕ Y) (V ⊕ X)) {he : List (U ⊕ Y)}
    (hd : he ∈ dom E) : he.map (liftEvent Y) ∈ dom (lift E) := by
  refine ⟨fun hc => empty_not_mem E
    (by rwa [List.map_eq_nil_iff.mp hc] at hd), ?_⟩
  intro l' hl' hne'
  obtain ⟨h₀, hpre, rfl⟩ := prefix_map_liftEvent hl'
  have h₀ne : h₀ ≠ [] := fun hc => hne' (by rw [hc]; rfl)
  have h₀d : h₀ ∈ dom E := prefix_closed E hpre h₀ne hd
  rcases List.eq_nil_or_concat h₀ with rfl | ⟨h₁, e, rfl⟩
  · exact absurd rfl h₀ne
  · rw [List.concat_eq_append] at h₀d ⊢
    have h₁pre : h₁ = [] ∨ h₁ ∈ dom E := by
      rcases List.eq_nil_or_concat h₁ with rfl | ⟨_, _, rfl⟩
      · exact Or.inl rfl
      · exact Or.inr (prefix_closed E (List.prefix_append _ _)
          (by simp) h₀d)
    show (ConverterImpl.engineRaw (liftImpl E)
      ((h₁ ++ [e]).map (liftEvent Y))).Dom
    rw [List.map_append, List.map_cons, List.map_nil,
      ConverterImpl.engineRaw_concat, state_lift_map E h₁ h₁pre,
      Part.bind_some, liftImpl_step_map]
    exact h₀d

/-- The lifted domain test agrees with the typed one on mapped
histories. -/
theorem mem_dom_lift_iff (E : DDS (U ⊕ Y) (V ⊕ X)) {he : List (U ⊕ Y)}
    {e : U ⊕ Y} (hok : he = [] ∨ he ∈ dom E) :
    (he.map (liftEvent Y)) ++ [liftEvent Y e] ∈ dom (lift E) ↔
      he ++ [e] ∈ dom E := by
  constructor
  · intro h
    have hokl : he.map (liftEvent Y) = [] ∨
        he.map (liftEvent Y) ∈ dom (lift E) := by
      rcases hok with rfl | hok
      · exact Or.inl rfl
      · exact Or.inr (mem_dom_lift_map E hok)
    have hraw := (mem_dom_validate_concat hokl (liftEvent Y e)).mp h
    rw [ConverterImpl.engineRaw_concat, state_lift_map E he hok,
      Part.bind_some, liftImpl_step_map] at hraw
    exact hraw
  · intro h
    have := mem_dom_lift_map E (he := he ++ [e]) h
    rwa [List.map_append, List.map_cons, List.map_nil] at this

/-- The lifted converter's output on mapped histories: the typed output,
its request included. -/
theorem output_lift_map (E : DDS (U ⊕ Y) (V ⊕ X)) {he : List (U ⊕ Y)}
    {e : U ⊕ Y} (hok : he = [] ∨ he ∈ dom E)
    (hE : he ++ [e] ∈ dom E)
    (h : (he.map (liftEvent Y)) ++ [liftEvent Y e] ∈ dom (lift E)) :
    output (lift E) ((he.map (liftEvent Y)) ++ [liftEvent Y e]) h =
      Sum.map id (encode X) (output E (he ++ [e]) hE) := by
  apply output_validate_of_eq_some
  rw [ConverterImpl.engineRaw_concat, state_lift_map E he hok,
    Part.bind_some, liftImpl_step_map]
  refine Part.eq_some_iff.mpr ?_
  refine (Part.mem_map_iff _).mpr ?_
  refine ⟨(he ++ [e], Sum.map id (encode X) (output E (he ++ [e]) hE)),
    ?_, rfl⟩
  exact (Part.mem_map_iff _).mpr ⟨output E (he ++ [e]) hE,
    Part.get_mem hE, rfl⟩

/-- **Transparency, round form**: one round of the lifted converter
against the included resource is one round of the converter against the
typed resource, transported by one `Part.map` equation. -/
theorem serve_lift (E : DDS (U ⊕ Y) (V ⊕ X)) (R : DDS X Y) :
    ∀ (n : ℕ) (he : List (U ⊕ Y)) (e : U ⊕ Y) (lx : List X),
      (he = [] ∨ he ∈ dom E) →
      Connect.serve (lift E) (ofTyped R) n
          ((he.map (liftEvent Y)) ++ [liftEvent Y e],
            lx.map (encode X)) =
        (Connect.serve E R n (he ++ [e], lx)).map
          (fun q => (q.1, (q.2.1.map (liftEvent Y),
            q.2.2.map (encode X)))) := by
  intro n
  induction n with
  | zero =>
      intro he e lx hok
      show Part.none = Part.map _ Part.none
      simp
  | succ n ih =>
      intro he e lx hok
      rw [Connect.serve_succ, Connect.serve_succ]
      by_cases hE : he ++ [e] ∈ dom E
      · rw [dif_pos ((mem_dom_lift_iff E hok).mpr hE), dif_pos hE,
          output_lift_map E hok hE]
        rcases hout : output E (he ++ [e]) hE with v | x
        · rw [Sum.map_inl]
          show Part.some (v, ((he.map (liftEvent Y)) ++ [liftEvent Y e],
            lx.map (encode X))) = _
          rw [Sum.elim_inl, Part.map_some]
          refine congrArg Part.some ?_
          refine Prod.ext rfl (Prod.ext ?_ rfl)
          show (he.map (liftEvent Y)) ++ [liftEvent Y e] =
            (he ++ [e]).map (liftEvent Y)
          rw [List.map_append, List.map_cons, List.map_nil]
        · rw [Sum.map_inr]
          rw [Sum.elim_inr, Sum.elim_inr]
          have hmap : (lx.map (encode X)) ++ [encode X x] =
              (lx ++ [x]).map (encode X) := by
            simp
          by_cases hR : lx ++ [x] ∈ dom R
          · have hT : (lx.map (encode X)) ++ [encode X x] ∈
                dom (ofTyped R) := by
              rw [hmap]
              exact (mem_dom_ofTyped_encode (by simp)).mpr hR
            have hT' : (lx ++ [x]).map (encode X) ∈ dom (ofTyped R) := by
              rw [← hmap]
              exact hT
            have hout' : output (ofTyped R)
                ((lx.map (encode X)) ++ [encode X x]) hT =
                encode Y (output R (lx ++ [x]) hR) := by
              rw [output_congr (ofTyped R) hmap hT hT']
              exact output_ofTyped_encode hR hT'
            rw [dif_pos hT, dif_pos hR, hout']
            have hok' : he ++ [e] = [] ∨ he ++ [e] ∈ dom E := Or.inr hE
            have := ih (he ++ [e]) (Sum.inr (output R (lx ++ [x]) hR))
              (lx ++ [x]) hok'
            rw [show ((he ++ [e]).map (liftEvent Y)) ++
                [liftEvent Y (Sum.inr (output R (lx ++ [x]) hR))] =
                ((he.map (liftEvent Y)) ++ [liftEvent Y e]) ++
                  [Sum.inr (encode Y (output R (lx ++ [x]) hR))] by
              simp [liftEvent]] at this
            rw [show (lx ++ [x]).map (encode X) =
              (lx.map (encode X)) ++ [encode X x] from hmap.symm] at this
            exact this
          · have hT : (lx.map (encode X)) ++ [encode X x] ∉
                dom (ofTyped R) := by
              rw [hmap]
              exact fun hc => hR
                ((mem_dom_ofTyped_encode (by simp)).mp hc)
            rw [dif_neg hT, dif_neg hR]
            show Part.none = Part.map _ Part.none
            simp
      · rw [dif_neg (fun hc => hE ((mem_dom_lift_iff E hok).mp hc)),
          dif_neg hE]
        show Part.none = Part.map _ Part.none
        simp

/-- **Transparency, run form**. -/
theorem runAux_lift (E : DDS (U ⊕ Y) (V ⊕ X)) (R : DDS X Y) (n : ℕ) :
    ∀ (us : List U) (he : List (U ⊕ Y)) (lx : List X),
      (he = [] ∨ he ∈ dom E) →
      Connect.runAux (lift E) (ofTyped R) n us
          (he.map (liftEvent Y), lx.map (encode X)) =
        (Connect.runAux E R n us (he, lx)).map
          (fun q => (q.1, (q.2.1.map (liftEvent Y),
            q.2.2.map (encode X)))) := by
  intro us
  induction us with
  | nil =>
      intro he lx hok
      show Part.none = Part.map _ Part.none
      simp
  | cons u t ih =>
      intro he lx hok
      cases t with
      | nil =>
          rw [Connect.runAux_singleton, Connect.runAux_singleton]
          exact serve_lift E R n he (Sum.inl u) lx hok
      | cons u' t' =>
          rw [Connect.runAux_cons_cons, Connect.runAux_cons_cons]
          rw [show (he.map (liftEvent Y), lx.map (encode X)).1 ++
              [Sum.inl u] =
              (he.map (liftEvent Y)) ++ [liftEvent Y (Sum.inl u)]
              from rfl,
            serve_lift E R n he (Sum.inl u) lx hok]
          by_cases hd : (Connect.serve E R n
              ((he, lx).1 ++ [Sum.inl u], (he, lx).2)).Dom
          · obtain ⟨q, hq⟩ := Part.dom_iff_mem.mp hd
            have hqe : Connect.serve E R n
                ((he, lx).1 ++ [Sum.inl u], (he, lx).2) =
                Part.some q := Part.eq_some_iff.mpr hq
            rw [hqe, Part.map_some, Part.bind_some, Part.bind_some]
            rcases q with ⟨v, he', lx'⟩
            have hok' : he' = [] ∨ he' ∈ dom E :=
              Or.inr (Connect.serve_final_dom hq)
            have := ih he' lx' hok'
            exact this
          · have hnone : Connect.serve E R n
                ((he, lx).1 ++ [Sum.inl u], (he, lx).2) = Part.none :=
              Part.eq_none_iff'.mpr hd
            rw [hnone]
            show (Part.map _ Part.none).bind _ = Part.map _ (Part.none.bind _)
            simp

/-- **Attachment commutes with inclusion**: interpreting the lifted
converter against the included resource is interpreting the converter
against the typed resource.  The re-seating theorem of the whole
section. -/
theorem connect_lift (E : DDS (U ⊕ Y) (V ⊕ X)) (R : DDS X Y) :
    connect (lift E) (ofTyped R) = connect E R := by
  apply Subtype.ext
  funext us
  have hrun : ∀ n, Connect.runAux (lift E) (ofTyped R) n us ([], []) =
      (Connect.runAux E R n us ([], [])).map
        (fun q => (q.1, (q.2.1.map (liftEvent Y),
          q.2.2.map (encode X)))) := fun n =>
    runAux_lift E R n us [] [] (Or.inl rfl)
  refine Part.ext' ?_ ?_
  · constructor
    · rintro ⟨n, hn⟩
      rw [hrun n] at hn
      exact ⟨n, hn⟩
    · rintro ⟨n, hn⟩
      refine ⟨n, ?_⟩
      rw [hrun n]
      exact hn
  · intro h₁ h₂
    have hd₂ : (Connect.runAux E R (Nat.find h₁) us ([], [])).Dom := by
      have := Nat.find_spec h₁
      rwa [hrun (Nat.find h₁)] at this
    have hval : (Connect.runAux E R (Nat.find h₁) us ([], [])) =
        (Connect.runAux E R (Nat.find h₂) us ([], [])) := by
      rw [← Connect.runAux_mono (le_max_left (Nat.find h₁) (Nat.find h₂))
        hd₂,
        Connect.runAux_mono (le_max_right (Nat.find h₁) (Nat.find h₂))
        (Nat.find_spec h₂)]
    show ((Connect.runAux (lift E) (ofTyped R) (Nat.find h₁) us
      ([], [])).get (Nat.find_spec h₁)).1 =
      ((Connect.runAux E R (Nat.find h₂) us ([], [])).get
        (Nat.find_spec h₂)).1
    obtain ⟨q, hq⟩ := Part.dom_iff_mem.mp hd₂
    have hqe := Part.eq_some_iff.mpr hq
    rw [Part.get_eq_of_mem
        (by
          rw [hrun (Nat.find h₁), hqe, Part.map_some]
          exact Part.mem_some _)
        (Nat.find_spec h₁),
      Part.get_eq_of_mem
        (by
          rw [← hval, hqe]
          exact Part.mem_some _)
        (Nat.find_spec h₂)]

/-- The typed view's output at an accepted frontier. -/
theorem output_toTyped_concat {X Y : Type u} {R : DDS Uni.{u} Uni.{u}}
    {lx : List X} {x : X}
    (hR : ((lx ++ [x]).map (encode X)) ∈ dom R)
    (hdec : (decode Y (output R ((lx ++ [x]).map (encode X)) hR)).Dom)
    (h : lx ++ [x] ∈ dom (toTyped X Y R)) :
    output (toTyped X Y R) (lx ++ [x]) h =
      (decode Y (output R ((lx ++ [x]).map (encode X)) hR)).get hdec := by
  apply output_validate_of_eq_some
  show (R.1 ((lx ++ [x]).map (encode X))).bind (decode Y) = Part.some _
  refine Part.eq_some_iff.mpr ?_
  exact Part.mem_bind_iff.mpr
    ⟨output R ((lx ++ [x]).map (encode X)) hR, Part.get_mem hR,
      Part.get_mem hdec⟩

/-- After an undecodable reply the lifted converter is stuck: the
attachment is undefined from that state on. -/
theorem serve_lift_undecodable (E : DDS (U ⊕ Y) (V ⊕ X))
    (R' : DDS Uni.{u} Uni.{u}) (n : ℕ) (he : List (U ⊕ Y)) (e : U ⊕ Y)
    (hE : he ++ [e] ∈ dom E) (q : Uni.{u}) (hdec : ¬(decode Y q).Dom)
    (rh : List Uni.{u}) :
    Connect.serve (lift E) R' n
      (((he.map (liftEvent Y)) ++ [liftEvent Y e]) ++ [Sum.inr q], rh) =
      Part.none := by
  cases n with
  | zero => rfl
  | succ n =>
      rw [Connect.serve_succ, dif_neg]
      intro hc
      have hraw := hc.2 _ (List.prefix_refl _) hc.1
      rw [show (he.map (liftEvent Y)) ++ [liftEvent Y e] =
          (he ++ [e]).map (liftEvent Y) by
        rw [List.map_append, List.map_cons, List.map_nil]] at hraw
      rw [ConverterImpl.engineRaw_concat,
        state_lift_map E (he ++ [e]) (Or.inr hE), Part.bind_some] at hraw
      exact hdec hraw.fst

/-- **Transparency for bare resources, round form**: a round of the lifted
converter against any element of Φ is a round of the converter against the
resource's typed view. -/
theorem serve_lift_bare (E : DDS (U ⊕ Y) (V ⊕ X))
    (R : DDS Uni.{u} Uni.{u}) :
    ∀ (n : ℕ) (he : List (U ⊕ Y)) (e : U ⊕ Y) (lx : List X),
      (he = [] ∨ he ∈ dom E) → (lx = [] ∨ lx ∈ dom (toTyped X Y R)) →
      Connect.serve (lift E) R n
          ((he.map (liftEvent Y)) ++ [liftEvent Y e],
            lx.map (encode X)) =
        (Connect.serve E (toTyped X Y R) n (he ++ [e], lx)).map
          (fun q => (q.1, (q.2.1.map (liftEvent Y),
            q.2.2.map (encode X)))) := by
  intro n
  induction n with
  | zero =>
      intro he e lx hok hlx
      show Part.none = Part.map _ Part.none
      simp
  | succ n ih =>
      intro he e lx hok hlx
      rw [Connect.serve_succ, Connect.serve_succ]
      by_cases hE : he ++ [e] ∈ dom E
      · rw [dif_pos ((mem_dom_lift_iff E hok).mpr hE), dif_pos hE,
          output_lift_map E hok hE]
        rcases hout : output E (he ++ [e]) hE with v | x
        · rw [Sum.map_inl]
          show Part.some (v, ((he.map (liftEvent Y)) ++ [liftEvent Y e],
            lx.map (encode X))) = _
          rw [Sum.elim_inl, Part.map_some]
          refine congrArg Part.some ?_
          refine Prod.ext rfl (Prod.ext ?_ rfl)
          show (he.map (liftEvent Y)) ++ [liftEvent Y e] =
            (he ++ [e]).map (liftEvent Y)
          rw [List.map_append, List.map_cons, List.map_nil]
        · rw [Sum.map_inr, Sum.elim_inr, Sum.elim_inr]
          have hmap : (lx.map (encode X)) ++ [encode X x] =
              (lx ++ [x]).map (encode X) := by
            simp
          by_cases hRB : (lx.map (encode X)) ++ [encode X x] ∈ dom R
          · have hRB' : (lx ++ [x]).map (encode X) ∈ dom R := by
              rw [← hmap]
              exact hRB
            by_cases hdec : (decode Y (output R
                ((lx ++ [x]).map (encode X)) hRB')).Dom
            · -- decodable reply: both sides advance in lockstep
              have hT : lx ++ [x] ∈ dom (toTyped X Y R) := by
                refine (mem_dom_validate_concat hlx x).mpr ?_
                exact ⟨hRB', hdec⟩
              set y := (decode Y (output R
                ((lx ++ [x]).map (encode X)) hRB')).get hdec with hy
              have hq : output R ((lx.map (encode X)) ++ [encode X x])
                  hRB = encode Y y := by
                rw [output_congr R hmap hRB hRB', hy]
                exact (encode_decode _ hdec).symm
              have hout' : output (toTyped X Y R) (lx ++ [x]) hT = y :=
                output_toTyped_concat hRB' hdec hT
              rw [dif_pos hRB, dif_pos hT, hq, hout']
              have := ih (he ++ [e]) (Sum.inr y) (lx ++ [x])
                (Or.inr hE) (Or.inr hT)
              rw [show ((he ++ [e]).map (liftEvent Y)) ++
                  [liftEvent Y (Sum.inr y)] =
                  ((he.map (liftEvent Y)) ++ [liftEvent Y e]) ++
                    [Sum.inr (encode Y y)] by
                simp [liftEvent]] at this
              rw [show (lx ++ [x]).map (encode X) =
                (lx.map (encode X)) ++ [encode X x] from hmap.symm] at this
              exact this
            · -- undecodable reply: both sides are undefined
              have hT : lx ++ [x] ∉ dom (toTyped X Y R) := by
                intro hc
                exact hdec ((mem_dom_validate_concat hlx x).mp hc).snd
              rw [dif_pos hRB, dif_neg hT]
              rw [show ((he.map (liftEvent Y)) ++ [liftEvent Y e]) ++
                  [Sum.inr (output R
                    ((lx.map (encode X)) ++ [encode X x]) hRB)] =
                  ((he.map (liftEvent Y)) ++ [liftEvent Y e]) ++
                  [Sum.inr (output R
                    ((lx.map (encode X)) ++ [encode X x]) hRB)] from rfl,
                serve_lift_undecodable E R n he e hE _
                  (by
                    intro hc
                    refine hdec ?_
                    rwa [output_congr R hmap.symm hRB' hRB]) _]
              show Part.none = Part.map _ Part.none
              simp
          · have hT : lx ++ [x] ∉ dom (toTyped X Y R) := by
              intro hc
              have := ((mem_dom_validate_concat hlx x).mp hc).fst
              exact hRB (by rwa [← hmap] at this)
            rw [dif_neg hRB, dif_neg hT]
            show Part.none = Part.map _ Part.none
            simp
      · rw [dif_neg (fun hc => hE ((mem_dom_lift_iff E hok).mp hc)),
          dif_neg hE]
        show Part.none = Part.map _ Part.none
        simp

/-- **Transparency for bare resources, run form**. -/
theorem runAux_lift_bare (E : DDS (U ⊕ Y) (V ⊕ X))
    (R : DDS Uni.{u} Uni.{u}) (n : ℕ) :
    ∀ (us : List U) (he : List (U ⊕ Y)) (lx : List X),
      (he = [] ∨ he ∈ dom E) → (lx = [] ∨ lx ∈ dom (toTyped X Y R)) →
      Connect.runAux (lift E) R n us
          (he.map (liftEvent Y), lx.map (encode X)) =
        (Connect.runAux E (toTyped X Y R) n us (he, lx)).map
          (fun q => (q.1, (q.2.1.map (liftEvent Y),
            q.2.2.map (encode X)))) := by
  intro us
  induction us with
  | nil =>
      intro he lx hok hlx
      show Part.none = Part.map _ Part.none
      simp
  | cons u t ih =>
      intro he lx hok hlx
      cases t with
      | nil =>
          rw [Connect.runAux_singleton, Connect.runAux_singleton]
          exact serve_lift_bare E R n he (Sum.inl u) lx hok hlx
      | cons u' t' =>
          rw [Connect.runAux_cons_cons, Connect.runAux_cons_cons]
          rw [show (he.map (liftEvent Y), lx.map (encode X)).1 ++
              [Sum.inl u] =
              (he.map (liftEvent Y)) ++ [liftEvent Y (Sum.inl u)]
              from rfl,
            serve_lift_bare E R n he (Sum.inl u) lx hok hlx]
          by_cases hd : (Connect.serve E (toTyped X Y R) n
              ((he, lx).1 ++ [Sum.inl u], (he, lx).2)).Dom
          · obtain ⟨q, hq⟩ := Part.dom_iff_mem.mp hd
            have hqe : Connect.serve E (toTyped X Y R) n
                ((he, lx).1 ++ [Sum.inl u], (he, lx).2) =
                Part.some q := Part.eq_some_iff.mpr hq
            rw [hqe, Part.map_some, Part.bind_some, Part.bind_some]
            rcases q with ⟨v, he', lx'⟩
            have hok' : he' = [] ∨ he' ∈ dom E :=
              Or.inr (Connect.serve_final_dom hq)
            have hlx' : lx' = [] ∨ lx' ∈ dom (toTyped X Y R) := by
              rcases Connect.serve_rh_dom hq with heq | hmem
              · rw [show lx' = lx from heq]
                exact hlx
              · exact Or.inr hmem
            exact ih he' lx' hok' hlx'
          · have hnone : Connect.serve E (toTyped X Y R) n
                ((he, lx).1 ++ [Sum.inl u], (he, lx).2) = Part.none :=
              Part.eq_none_iff'.mpr hd
            rw [hnone]
            show (Part.map _ Part.none).bind _ =
              Part.map _ (Part.none.bind _)
            simp

/-- **Transparency for bare resources**: attaching a lifted converter to
any element of Φ is attaching the converter to the resource's typed view.
The §3.3 statements therefore hold on ALL of Φ. -/
theorem connect_lift_bare (E : DDS (U ⊕ Y) (V ⊕ X))
    (R : DDS Uni.{u} Uni.{u}) :
    connect (lift E) R = connect E (toTyped X Y R) := by
  apply Subtype.ext
  funext us
  have hrun : ∀ n, Connect.runAux (lift E) R n us ([], []) =
      (Connect.runAux E (toTyped X Y R) n us ([], [])).map
        (fun q => (q.1, (q.2.1.map (liftEvent Y),
          q.2.2.map (encode X)))) := fun n =>
    runAux_lift_bare E R n us [] [] (Or.inl rfl) (Or.inl rfl)
  refine Part.ext' ?_ ?_
  · constructor
    · rintro ⟨n, hn⟩
      rw [hrun n] at hn
      exact ⟨n, hn⟩
    · rintro ⟨n, hn⟩
      refine ⟨n, ?_⟩
      rw [hrun n]
      exact hn
  · intro h₁ h₂
    have hd₂ : (Connect.runAux E (toTyped X Y R) (Nat.find h₁) us
        ([], [])).Dom := by
      have := Nat.find_spec h₁
      rwa [hrun (Nat.find h₁)] at this
    have hval : (Connect.runAux E (toTyped X Y R) (Nat.find h₁) us
        ([], [])) =
        (Connect.runAux E (toTyped X Y R) (Nat.find h₂) us ([], [])) := by
      rw [← Connect.runAux_mono (le_max_left (Nat.find h₁) (Nat.find h₂))
        hd₂,
        Connect.runAux_mono (le_max_right (Nat.find h₁) (Nat.find h₂))
        (Nat.find_spec h₂)]
    show ((Connect.runAux (lift E) R (Nat.find h₁) us
      ([], [])).get (Nat.find_spec h₁)).1 =
      ((Connect.runAux E (toTyped X Y R) (Nat.find h₂) us ([], [])).get
        (Nat.find_spec h₂)).1
    obtain ⟨q, hq⟩ := Part.dom_iff_mem.mp hd₂
    have hqe := Part.eq_some_iff.mpr hq
    rw [Part.get_eq_of_mem
        (by
          rw [hrun (Nat.find h₁), hqe, Part.map_some]
          exact Part.mem_some _)
        (Nat.find_spec h₁),
      Part.get_eq_of_mem
        (by
          rw [← hval, hqe]
          exact Part.mem_some _)
        (Nat.find_spec h₂)]

/-- **MR16 §3.3's composition-order independence, on all of Φ**:
converters attached at distinct interfaces commute on every element — the
fixed-signature matrix, transported by bare transparency. -/
theorem connectPhi_comm {P A B : Type u} {i j : P} (hij : i ≠ j)
    (E F : DDS (A ⊕ B) (B ⊕ A)) (R : DDS Uni.{u} Uni.{u}) :
    connectPhi (liftAt i E) (connectPhi (liftAt j F) R) =
      connectPhi (liftAt j F) (connectPhi (liftAt i E) R) := by
  show ofTyped (connect (lift (liftAt i E))
      (ofTyped (connect (lift (liftAt j F)) R))) =
    ofTyped (connect (lift (liftAt j F))
      (ofTyped (connect (lift (liftAt i E)) R)))
  rw [connect_lift_bare (liftAt j F) R, connect_lift_bare (liftAt i E) R,
    connect_lift (liftAt i E) (connect (liftAt j F)
      (toTyped (P × A) B R)),
    connect_lift (liftAt j F) (connect (liftAt i E)
      (toTyped (P × A) B R))]
  exact congrArg ofTyped
    (attachEngine_comm hij E F (toTyped (P × A) B R))

end Transparency

/-! ### The identity law (MR16 §3.3)

Attaching the lifted identity converter to an included resource restores
it: the interpreter's rounds are the inclusion round trip, which the
`Phi.lean` lemmas make invisible. -/

section Identity

variable {X Y : Type u}

theorem liftImpl_id_onQuery (s : List (X ⊕ Y)) (x : X) :
    (liftImpl (idEngine (X := X) (Y := Y))).onQuery s x =
      Part.some (s ++ [Sum.inl x], Sum.inr (encode X x)) := by
  have hd : s ++ [Sum.inl x] ∈ dom (idEngine (X := X) (Y := Y)) := by
    show _ ≠ []
    simp
  have hout : output (idEngine (X := X) (Y := Y)) (s ++ [Sum.inl x]) hd =
      Sum.inr x := by
    simp [idEngine]
  have hmem : Sum.inr x ∈
      (idEngine (X := X) (Y := Y)).1 (s ++ [Sum.inl x]) :=
    hout ▸ Part.get_mem hd
  refine Part.eq_some_iff.mpr ?_
  exact (Part.mem_map_iff _).mpr ⟨Sum.inr x, hmem, rfl⟩

theorem liftImpl_id_onReply (s : List (X ⊕ Y)) (y : Y) :
    (liftImpl (idEngine (X := X) (Y := Y))).onReply s (encode Y y) =
      Part.some (s ++ [Sum.inr y], Sum.inl y) := by
  show ((decode Y (encode Y y)).bind fun y' =>
    ((idEngine (X := X) (Y := Y)).1 (s ++ [Sum.inr y'])).map fun out =>
      (s ++ [Sum.inr y'], Sum.map id (encode X) out)) = _
  rw [decode_encode, Part.bind_some]
  have hd : s ++ [Sum.inr y] ∈ dom (idEngine (X := X) (Y := Y)) := by
    show _ ≠ []
    simp
  have hout : output (idEngine (X := X) (Y := Y)) (s ++ [Sum.inr y]) hd =
      Sum.inl y := by
    simp [idEngine]
  have hmem : Sum.inl y ∈
      (idEngine (X := X) (Y := Y)).1 (s ++ [Sum.inr y]) :=
    hout ▸ Part.get_mem hd
  refine Part.eq_some_iff.mpr ?_
  exact (Part.mem_map_iff _).mpr ⟨Sum.inl y, hmem, rfl⟩

/-- The state after a round, defined and explicit. -/
theorem state_lift_id_round (s : List (X ⊕ Y)) (eh : List (X ⊕ Uni.{u}))
    (x : X) (y : Y)
    (hs : (liftImpl (idEngine (X := X) (Y := Y))).state eh = Part.some s) :
    (liftImpl (idEngine (X := X) (Y := Y))).state
        (eh ++ [Sum.inl x, Sum.inr (encode Y y)]) =
      Part.some ((s ++ [Sum.inl x]) ++ [Sum.inr y]) := by
  rw [show eh ++ [Sum.inl x, Sum.inr (encode Y y)] =
      (eh ++ [Sum.inl x]) ++ [Sum.inr (encode Y y)] by simp,
    ConverterImpl.state_append, ConverterImpl.state_append, hs,
    Part.bind_some]
  rw [show (liftImpl (idEngine (X := X) (Y := Y))).step s (Sum.inl x) =
      (liftImpl (idEngine (X := X) (Y := Y))).onQuery s x from rfl,
    liftImpl_id_onQuery, Part.map_some, Part.bind_some]
  rw [show (liftImpl (idEngine (X := X) (Y := Y))).step (s ++ [Sum.inl x])
      (Sum.inr (encode Y y)) =
      (liftImpl (idEngine (X := X) (Y := Y))).onReply (s ++ [Sum.inl x])
        (encode Y y) from rfl,
    liftImpl_id_onReply, Part.map_some]

/-- **The round receipt for the lifted identity**: one round is one query
to the included resource, through the inclusion round trip. -/
theorem serve_lift_id (S : DDS X Y) (n : ℕ) (eh : List (X ⊕ Uni.{u}))
    (lx : List X)
    (hok : eh = [] ∨ eh ∈ dom (lift (idEngine (X := X) (Y := Y))))
    (hst : ∃ s, (liftImpl (idEngine (X := X) (Y := Y))).state eh =
      Part.some s) (x : X) :
    Connect.serve (lift (idEngine (X := X) (Y := Y))) (ofTyped S) (n + 2)
        (eh ++ [Sum.inl x], lx.map (encode X)) =
      if hS : lx ++ [x] ∈ dom S then
        Part.some (output S (lx ++ [x]) hS,
          (eh ++ [Sum.inl x,
            Sum.inr (encode Y (output S (lx ++ [x]) hS))],
            (lx ++ [x]).map (encode X)))
      else Part.none := by
  obtain ⟨s, hs⟩ := hst
  rw [← lift_engine, ConverterImpl.serve_step _ _ (n + 1) eh (Sum.inl x)
    _ (by rw [lift_engine]; exact hok)]
  rw [hs, Part.bind_some]
  rw [show (liftImpl (idEngine (X := X) (Y := Y))).step s (Sum.inl x) =
      (liftImpl (idEngine (X := X) (Y := Y))).onQuery s x from rfl,
    liftImpl_id_onQuery, Part.bind_some]
  have hmap : (lx.map (encode X)) ++ [encode X x] =
      (lx ++ [x]).map (encode X) := by
    simp
  by_cases hS : lx ++ [x] ∈ dom S
  · have hT : (lx.map (encode X)) ++ [encode X x] ∈ dom (ofTyped S) := by
      rw [hmap]
      exact (mem_dom_ofTyped_encode (by simp)).mpr hS
    have hT' : (lx ++ [x]).map (encode X) ∈ dom (ofTyped S) := by
      rw [← hmap]
      exact hT
    have hout : output (ofTyped S) ((lx.map (encode X)) ++ [encode X x])
        hT = encode Y (output S (lx ++ [x]) hS) := by
      rw [output_congr (ofTyped S) hmap hT hT']
      exact output_ofTyped_encode hS hT'
    rw [ConverterImpl.run_request _ _ _ _ _ _ _ hT, hout,
      liftImpl_id_onReply, Part.bind_some, ConverterImpl.run_answer,
      dif_pos hS]
    rw [Part.map_some, hmap]
    show Part.some (output S (lx ++ [x]) hS,
      ((eh ++ [Sum.inl x]) ++
        [Sum.inr (encode Y (output S (lx ++ [x]) hS))],
        (lx ++ [x]).map (encode X))) = _
    rw [List.append_assoc]
    rfl
  · have hT : (lx.map (encode X)) ++ [encode X x] ∉ dom (ofTyped S) := by
      rw [hmap]
      exact fun hc => hS ((mem_dom_ofTyped_encode (by simp)).mp hc)
    rw [ConverterImpl.run_request_none _ _ _ _ _ _ _ hT, dif_neg hS]
    simp

/-- Runs of the lifted identity resolve at fuel 2, tracking the included
history. -/
theorem runAux_lift_id (S : DDS X Y) :
    ∀ (us : List X) (h : us ≠ []) (eh : List (X ⊕ Uni.{u})) (lx : List X)
      (hok : eh = [] ∨ eh ∈ dom (lift (idEngine (X := X) (Y := Y))))
      (hst : ∃ s, (liftImpl (idEngine (X := X) (Y := Y))).state eh =
        Part.some s)
      (hS : lx ++ us ∈ dom S),
      ∃ eh', Connect.runAux (lift (idEngine (X := X) (Y := Y)))
          (ofTyped S) 2 us (eh, lx.map (encode X)) =
        Part.some (output S (lx ++ us) hS,
          (eh', (lx ++ us).map (encode X))) := by
  intro us
  induction us with
  | nil => exact fun h => absurd rfl h
  | cons u t ih =>
      intro h eh lx hok hst hS
      cases t with
      | nil =>
          refine ⟨eh ++ [Sum.inl u,
            Sum.inr (encode Y (output S (lx ++ [u]) hS))], ?_⟩
          rw [Connect.runAux_singleton, serve_lift_id S 0 eh lx hok hst u,
            dif_pos hS]
      | cons u' t' =>
          have hpre : lx ++ [u] ∈ dom S :=
            prefix_closed S ⟨u' :: t', by simp⟩ (by simp) hS
          have hS' : (lx ++ [u]) ++ (u' :: t') ∈ dom S := by
            simpa [List.append_assoc] using hS
          obtain ⟨s, hs⟩ := hst
          have hstep := serve_lift_id S 0 eh lx hok ⟨s, hs⟩ u
          rw [dif_pos hpre] at hstep
          have hok' : eh ++ [Sum.inl u,
              Sum.inr (encode Y (output S (lx ++ [u]) hpre))] = [] ∨
              eh ++ [Sum.inl u,
                Sum.inr (encode Y (output S (lx ++ [u]) hpre))] ∈
                dom (lift (idEngine (X := X) (Y := Y))) := by
            refine Or.inr ?_
            have hmem : (output S (lx ++ [u]) hpre,
                (eh ++ [Sum.inl u,
                  Sum.inr (encode Y (output S (lx ++ [u]) hpre))],
                  (lx ++ [u]).map (encode X))) ∈
                Connect.serve (lift (idEngine (X := X) (Y := Y)))
                  (ofTyped S) 2 (eh ++ [Sum.inl u], lx.map (encode X)) := by
              rw [hstep]
              exact Part.mem_some _
            exact Connect.serve_final_dom hmem
          have hst' : ∃ s', (liftImpl (idEngine (X := X) (Y := Y))).state
              (eh ++ [Sum.inl u,
                Sum.inr (encode Y (output S (lx ++ [u]) hpre))]) =
              Part.some s' :=
            ⟨_, state_lift_id_round s eh u (output S (lx ++ [u]) hpre) hs⟩
          obtain ⟨eh', heq⟩ := ih (by simp) _ (lx ++ [u]) hok' hst' hS'
          refine ⟨eh', ?_⟩
          rw [Connect.runAux_cons_cons, serve_lift_id S 0 eh lx hok
            ⟨s, hs⟩ u, dif_pos hpre, Part.bind_some, heq]
          have hl : (lx ++ [u]) ++ (u' :: t') = lx ++ (u :: u' :: t') := by
            simp
          refine congrArg Part.some ?_
          refine Prod.ext (output_congr S hl hS' hS) (Prod.ext rfl ?_)
          show ((lx ++ [u]) ++ (u' :: t')).map (encode X) = _
          rw [hl]

/-- A resolved round, characterized from a mere domain fact. -/
theorem serve_lift_id_dom (S : DDS X Y) :
    ∀ {n : ℕ} {eh : List (X ⊕ Uni.{u})} {lx : List X},
      (eh = [] ∨ eh ∈ dom (lift (idEngine (X := X) (Y := Y)))) →
      (∃ s, (liftImpl (idEngine (X := X) (Y := Y))).state eh =
        Part.some s) → ∀ {x : X},
      (Connect.serve (lift (idEngine (X := X) (Y := Y))) (ofTyped S) n
        (eh ++ [Sum.inl x], lx.map (encode X))).Dom →
      ∃ hS : lx ++ [x] ∈ dom S,
        Connect.serve (lift (idEngine (X := X) (Y := Y))) (ofTyped S) n
          (eh ++ [Sum.inl x], lx.map (encode X)) =
        Part.some (output S (lx ++ [x]) hS,
          (eh ++ [Sum.inl x,
            Sum.inr (encode Y (output S (lx ++ [x]) hS))],
            (lx ++ [x]).map (encode X))) := by
  intro n
  match n with
  | 0 =>
      intro eh lx hok hst x h
      exact h.elim
  | 1 =>
      intro eh lx hok hst x h
      exfalso
      obtain ⟨s, hs⟩ := hst
      rw [← lift_engine, ConverterImpl.serve_step _ _ 0 eh (Sum.inl x)
        _ (by rw [lift_engine]; exact hok), hs, Part.bind_some] at h
      rw [show (liftImpl (idEngine (X := X) (Y := Y))).step s
          (Sum.inl x) =
          (liftImpl (idEngine (X := X) (Y := Y))).onQuery s x from rfl,
        liftImpl_id_onQuery, Part.bind_some] at h
      exact h.elim
  | n + 2 =>
      intro eh lx hok hst x h
      rw [serve_lift_id S n eh lx hok hst x] at h ⊢
      by_cases hS : lx ++ [x] ∈ dom S
      · exact ⟨hS, by rw [dif_pos hS]⟩
      · rw [dif_neg hS] at h
        exact h.elim

/-- Resolved runs certify the typed domain. -/
theorem runAux_lift_id_dom (S : DDS X Y) {n : ℕ} :
    ∀ (us : List X) {eh : List (X ⊕ Uni.{u})} {lx : List X},
      (eh = [] ∨ eh ∈ dom (lift (idEngine (X := X) (Y := Y)))) →
      (∃ s, (liftImpl (idEngine (X := X) (Y := Y))).state eh =
        Part.some s) →
      (Connect.runAux (lift (idEngine (X := X) (Y := Y))) (ofTyped S) n
        us (eh, lx.map (encode X))).Dom →
      lx ++ us ∈ dom S := by
  intro us
  induction us with
  | nil =>
      intro eh lx _ _ h
      exact h.elim
  | cons u t ih =>
      intro eh lx hok hst h
      cases t with
      | nil =>
          rw [Connect.runAux_singleton] at h
          obtain ⟨hS, -⟩ := serve_lift_id_dom S hok hst h
          exact hS
      | cons u' t' =>
          rw [Connect.runAux_cons_cons] at h
          obtain ⟨hserve, hrest⟩ := Part.bind_dom.mp h
          obtain ⟨hpre, heq⟩ := serve_lift_id_dom S hok hst hserve
          rw [Part.get_eq_of_mem (by rw [heq]; exact Part.mem_some _)
            hserve] at hrest
          obtain ⟨s, hs⟩ := hst
          have hok' : eh ++ [Sum.inl u,
              Sum.inr (encode Y (output S (lx ++ [u]) hpre))] = [] ∨
              eh ++ [Sum.inl u,
                Sum.inr (encode Y (output S (lx ++ [u]) hpre))] ∈
              dom (lift (idEngine (X := X) (Y := Y))) :=
            Or.inr (Connect.serve_final_dom
              (by rw [heq]; exact Part.mem_some _))
          have hst' : ∃ s', (liftImpl
              (idEngine (X := X) (Y := Y))).state
              (eh ++ [Sum.inl u,
                Sum.inr (encode Y (output S (lx ++ [u]) hpre))]) =
              Part.some s' :=
            ⟨_, state_lift_id_round s eh u (output S (lx ++ [u]) hpre) hs⟩
          have := ih hok' hst' hrest
          simpa [List.append_assoc] using this

/-- **MR16 §3.3's identity law, typed form**: attaching the lifted
identity converter to an included resource restores the typed system. -/
theorem connect_lift_id (S : DDS X Y) :
    connect (lift (idEngine (X := X) (Y := Y))) (ofTyped S) = S := by
  apply Subtype.ext
  funext us
  refine Part.ext' ?_ ?_
  · constructor
    · rintro ⟨n, hn⟩
      cases us with
      | nil => exact hn.elim
      | cons u t =>
          exact runAux_lift_id_dom (n := n) S (u :: t) (lx := [])
            (Or.inl rfl) ⟨[], rfl⟩ hn
    · intro h
      have hne : us ≠ [] := fun hc => empty_not_mem S (hc ▸ h)
      obtain ⟨eh', heq⟩ := runAux_lift_id S us hne [] []
        (Or.inl rfl) ⟨[], rfl⟩ (show ([] : List X) ++ us ∈ dom S from h)
      have heq' : Connect.runAux (lift (idEngine (X := X) (Y := Y)))
          (ofTyped S) 2 us ([], []) =
          Part.some (output S ([] ++ us)
            (show ([] : List X) ++ us ∈ dom S from h),
            (eh', ([] ++ us).map (encode X))) := heq
      exact ⟨2, by rw [heq']; trivial⟩
  · intro h₁ h₂
    have hne : us ≠ [] := fun hc => empty_not_mem S (hc ▸ h₂)
    obtain ⟨eh', heq⟩ := runAux_lift_id S us hne [] []
      (Or.inl rfl) ⟨[], rfl⟩ (show ([] : List X) ++ us ∈ dom S from h₂)
    have heq' : Connect.runAux (lift (idEngine (X := X) (Y := Y)))
        (ofTyped S) 2 us ([], []) =
        Part.some (output S ([] ++ us)
          (show ([] : List X) ++ us ∈ dom S from h₂),
          (eh', ([] ++ us).map (encode X))) := heq
    have h2d : (Connect.runAux (lift (idEngine (X := X) (Y := Y)))
        (ofTyped S) 2 us ([], [])).Dom := by
      rw [heq']
      trivial
    have hmax : Connect.runAux (lift (idEngine (X := X) (Y := Y)))
        (ofTyped S) (Nat.find h₁) us ([], []) =
        Connect.runAux (lift (idEngine (X := X) (Y := Y)))
          (ofTyped S) 2 us ([], []) := by
      rw [← Connect.runAux_mono (le_max_left (Nat.find h₁) 2)
        (Nat.find_spec h₁),
        Connect.runAux_mono (le_max_right (Nat.find h₁) 2) h2d]
    show ((Connect.runAux (lift (idEngine (X := X) (Y := Y)))
      (ofTyped S) (Nat.find h₁) us ([], [])).get
        (Nat.find_spec h₁)).1 = _
    rw [Part.get_eq_of_mem (by rw [hmax, heq']; exact Part.mem_some _)
      (Nat.find_spec h₁)]
    rfl

/-- **MR16 §3.3's identity law on Φ**: the identity converter's
endomorphism restores every included resource. -/
theorem connectPhi_id (S : DDS X Y) :
    connectPhi (idEngine (X := X) (Y := Y)) (ofTyped S) = ofTyped S := by
  show ofTyped (connect (lift (idEngine (X := X) (Y := Y)))
    (ofTyped S)) = _
  rw [connect_lift_id]

end Identity

end

end System

universe u

/-- **`connect` on Φ**: the endomorphism induced by a converter — the
generator family of Σ.  The converter is sampled independently of the
resource, both laws pushed along the deterministic interpreter. -/
noncomputable def connectPhi {U Y V X : Type u}
    (EL : PDS (U ⊕ Y) (V ⊕ X)) : Function.End Phi.{u} := fun R =>
  Probability.Distribution.fTransform
    (fun p : System.DDS (U ⊕ Y) (V ⊕ X) × System.DDS Uni.{u} Uni.{u} =>
      System.connectPhi p.1 p.2)
    (Probability.Distribution.prod EL R)

/-- The deterministic attachment endomorphism. -/
noncomputable def attach {U Y V X : Type u}
    (E : System.DDS (U ⊕ Y) (V ⊕ X)) : Function.End Phi.{u} :=
  Probability.Distribution.fTransform (System.connectPhi E)

/-! ### Blocking on Φ (MR16 §3.4)

On Φ an interface is a query set, so `⊣` blocks a `Set Uni`.  The merge
and unit laws descend from the system level by pushforward. -/

/-- MauRen16 §3.4's `⊣` on Φ. -/
noncomputable def block (Q : Set Uni.{u}) : Function.End Phi.{u} :=
  Probability.Distribution.fTransform (System.blockSet Q)

@[simp] theorem block_empty : block (∅ : Set Uni.{u}) = 1 := by
  funext R
  show Probability.Distribution.fTransform (System.blockSet ∅) R = R
  rw [show System.blockSet (∅ : Set Uni.{u}) =
      (id : System.DDS Uni.{u} Uni.{u} → System.DDS Uni.{u} Uni.{u})
      from funext fun S => System.blockSet_empty S,
    Probability.Distribution.fTransform_id]

/-- Blocks merge into the union — Σ-composition of `⊣`s is one `⊣`. -/
theorem block_block (Q₁ Q₂ : Set Uni.{u}) :
    block Q₁ * block Q₂ = block (Q₁ ∪ Q₂) := by
  funext R
  show Probability.Distribution.fTransform (System.blockSet Q₁)
    (Probability.Distribution.fTransform (System.blockSet Q₂) R) = _
  rw [Probability.Distribution.fTransform_fTransform]
  exact congrFun (congrArg _
    (funext fun S => System.blockSet_blockSet Q₁ Q₂ S)) R

/-- Blocks always commute. -/
theorem block_actCommute (Q₁ Q₂ : Set Uni.{u}) :
    AbstractCryptography.ActCommute Phi.{u} (block Q₁) (block Q₂) := by
  intro S
  show (block Q₁ * block Q₂) S = (block Q₂ * block Q₁) S
  rw [block_block, block_block, Set.union_comm]

/-- **The converter monoid Σ** (MR16 §3.3): the submonoid of
`Function.End Φ` generated by attachment of converters — systems with sum
signatures — at every signature, probabilistic and deterministic.
`id ∈ Σ` and closure under composition are the submonoid structure;
identity and order-independence are the theorems above. -/
noncomputable def converterMonoid : Submonoid (Function.End Phi.{u}) :=
  Submonoid.closure
    ({π | ∃ (U Y V X : Type u) (EL : PDS (U ⊕ Y) (V ⊕ X)),
        π = connectPhi EL} ∪
      {π | ∃ (U Y V X : Type u) (E : System.DDS (U ⊕ Y) (V ⊕ X)),
        π = attach E} ∪
      {π | ∃ Q : Set Uni.{u}, π = block Q})

theorem connectPhi_mem {U Y V X : Type u} (EL : PDS (U ⊕ Y) (V ⊕ X)) :
    connectPhi EL ∈ converterMonoid.{u} :=
  Submonoid.subset_closure (Or.inl (Or.inl ⟨U, Y, V, X, EL, rfl⟩))

theorem attach_mem {U Y V X : Type u} (E : System.DDS (U ⊕ Y) (V ⊕ X)) :
    attach E ∈ converterMonoid.{u} :=
  Submonoid.subset_closure (Or.inl (Or.inr ⟨U, Y, V, X, E, rfl⟩))

theorem block_mem (Q : Set Uni.{u}) : block Q ∈ converterMonoid.{u} :=
  Submonoid.subset_closure (Or.inr ⟨Q, rfl⟩)

/-- `id ∈ Σ`: the submonoid's unit. -/
example : (1 : Function.End Phi.{u}) ∈ converterMonoid.{u} :=
  Submonoid.one_mem _

/-- Σ is closed under composition: the submonoid's multiplication. -/
example (π σ : Function.End Phi.{u}) (hπ : π ∈ converterMonoid.{u})
    (hσ : σ ∈ converterMonoid.{u}) : π * σ ∈ converterMonoid.{u} :=
  mul_mem hπ hσ

/-- **The `ActCommute` receipt on Φ**: deterministic attachments at
distinct interfaces commute as endomorphisms of Φ — the abstract layer's
axiom, discharged for the whole carrier. -/
theorem attach_actCommute {P A B : Type u} {i j : P} (hij : i ≠ j)
    (E F : System.DDS (A ⊕ B) (B ⊕ A)) :
    AbstractCryptography.ActCommute Phi.{u}
      (attach (System.liftAt i E)) (attach (System.liftAt j F)) := by
  intro S
  show attach (System.liftAt i E) (attach (System.liftAt j F) S) =
    attach (System.liftAt j F) (attach (System.liftAt i E) S)
  unfold attach
  rw [Probability.Distribution.fTransform_fTransform,
    Probability.Distribution.fTransform_fTransform]
  exact congrFun (congrArg _
    (funext fun R => System.connectPhi_comm hij E F R)) S

/-- The attachment family satisfies the abstract grouping axiom, over all
of Φ. -/
theorem pairwiseOrderInvariant_attach {P A B : Type u} :
    AbstractCryptography.PairwiseOrderInvariant Phi.{u}
      (fun (i : P) (E : System.DDS (A ⊕ B) (B ⊕ A)) =>
        attach (System.liftAt i E)) :=
  fun _ _ hij E F => attach_actCommute hij E F

/-- **MR16 §7's grouping receipt on Φ**: converters attached within
disjoint interface sets are order-invariant as groups — the abstract
layer's `orderInvariant_attachedWithin` consumed at the one carrier, with
no new induction code. -/
theorem orderInvariant_attach {P A B : Type u} {Z₁ Z₂ : Set P}
    (h : Disjoint Z₁ Z₂) :
    AbstractCryptography.OrderInvariant Phi.{u}
      (AbstractCryptography.attachedWithin
        (fun (i : P) (E : System.DDS (A ⊕ B) (B ⊕ A)) =>
          attach (System.liftAt i E)) Z₁).subtype
      (AbstractCryptography.attachedWithin
        (fun (i : P) (E : System.DDS (A ⊕ B) (B ⊕ A)) =>
          attach (System.liftAt i E)) Z₂).subtype :=
  AbstractCryptography.orderInvariant_attachedWithin _
    pairwiseOrderInvariant_attach h

/-! ### Blocking an interface commutes with foreign attachment
(MR16 §3.4 meets §3.3) -/

/-- The preimage of an interface's included queries is the tag
cylinder. -/
theorem encode_preimage_interface {P A : Type u} (j : P) :
    System.encode (P × A) ⁻¹'
        {q : Uni.{u} | ∃ a : A, q = System.encode (P × A) (j, a)} =
      {p : P × A | p.1 ∈ ({j} : Set P)} := by
  ext ⟨p, a⟩
  simp only [Set.mem_preimage, Set.mem_setOf_eq, Set.mem_singleton_iff]
  constructor
  · rintro ⟨a', heq⟩
    exact congrArg Prod.fst (System.encode_injective (P × A) heq)
  · rintro rfl
    exact ⟨a, rfl⟩

/-- Blocking interface `j` commutes with attachment at `i ≠ j`, on every
element of Φ — the fixed-signature mixed cell transported through the
inclusion. -/
theorem blockSet_connectPhi_comm {P A B : Type u} {i j : P}
    (hij : i ≠ j) (E : System.DDS (A ⊕ B) (B ⊕ A))
    (R : System.DDS Uni.{u} Uni.{u}) :
    System.blockSet
        {q : Uni.{u} | ∃ a : A, q = System.encode (P × A) (j, a)}
        (System.connectPhi (System.liftAt i E) R) =
      System.connectPhi (System.liftAt i E)
        (System.blockSet
          {q : Uni.{u} | ∃ a : A, q = System.encode (P × A) (j, a)}
          R) := by
  show System.blockSet _
      (System.ofTyped
        (System.connect (System.lift (System.liftAt i E)) R)) =
    System.ofTyped (System.connect (System.lift (System.liftAt i E))
      (System.blockSet _ R))
  rw [System.connect_lift_bare (System.liftAt i E) R,
    System.connect_lift_bare (System.liftAt i E) (System.blockSet _ R),
    System.blockSet_ofTyped, encode_preimage_interface,
    System.toTyped_blockSet, encode_preimage_interface,
    ← System.block_eq_blockSet, ← System.block_eq_blockSet]
  exact congrArg System.ofTyped
    (System.attachEngine_block (by simp [hij])).symm

/-- The `ActCommute` receipt: interface-blocking and foreign attachment
commute as endomorphisms of Φ. -/
theorem block_attach_actCommute {P A B : Type u} {i j : P}
    (hij : i ≠ j) (E : System.DDS (A ⊕ B) (B ⊕ A)) :
    AbstractCryptography.ActCommute Phi.{u}
      (block {q : Uni.{u} | ∃ a : A, q = System.encode (P × A) (j, a)})
      (attach (System.liftAt i E)) := by
  intro S
  show block _ (attach (System.liftAt i E) S) =
    attach (System.liftAt i E) (block _ S)
  unfold block attach
  rw [Probability.Distribution.fTransform_fTransform,
    Probability.Distribution.fTransform_fTransform]
  exact congrFun (congrArg _
    (funext fun R => blockSet_connectPhi_comm hij E R)) S

end RandomSystems
