/-
Copyright (c) 2026 Trail of Bits. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import RandomSystems.System.MetricFullyDefined
import AbstractCryptography.Algebra.Star
import AbstractCryptography.Specification.Outbound

/-!
# MauRen16 §3.4 and §4 on the fully defined carrier

The converter-class relaxations of MauRen16 §3.4 — `𝓡* = 𝓡Σ`, the blocking
converter `⊣`, right-outboundness and `𝓡⟦` — together with §4.1's Lemmas 3
and 4 and §4.2's Lemma 5, instantiated at

* `Φ := Phi.{u}`, the fully defined carrier, with the `PseudoEMetricSpace`
  instance of `MetricFullyDefined.lean`; and
* `Σ := ↥converterMonoidAt`, the metric-facing converter monoid of the
  DRIFT-REPAIR's interface-indexed attachment `attachAt`.

The abstract algebra is already proved (`AbstractCryptography.Algebra.Star`);
what this file supplies is the *carrier* content the abstract statements ask
for as hypotheses, and which no RandomSystems module carried before:

* `converterMonoidWithin A` — MauRen16 §3.4's `Σ` **at one interface**: the
  sub-class of the metric-facing Σ generated by interface-local attachments
  whose interface *and* whose requests stay inside the query set `A`.  This is
  the `H` that `star` relaxes by, so that `𝓡*` is "an arbitrary converter at
  the adversary interface" and not "an arbitrary converter anywhere".
* `coe_commute_converterMonoidWithin` — MauRen16 §3.3's `(αR)β = α(Rβ)` for
  two whole classes at disjoint interfaces, which is the commutation premise
  of Lemma 3 (and, with `⊣`, of Lemma 4).  It is `attachAt_comm` lifted along
  the two closures, and nothing else.

The distance never appears in §3.4 itself; it enters at §4.2, where the
`IsNonexpandingSMul` instance registered in `MetricFullyDefined.lean` is what
lets the `ε`-relaxation and the `∗`-relaxation be interchanged.
-/

namespace RandomSystems

open scoped ENNReal

open AbstractCryptography (Specification Constructs Relaxation)

open scoped AbstractCryptography

open Probability (Distribution)

open Pointwise

universe u

noncomputable section

/-! ## MauRen16 §3.4's `Σ` at one interface

`star` relaxes by a *submonoid of the converter monoid*, and on this carrier
the converter monoid is `converterMonoidAt` — every interface at once.
MauRen16's `∗` is applied at the adversary interface only, so the class the
relaxation ranges over has to be cut down to it. -/

/-- **MauRen16 §3.4's admitted converter class at the interface `A`** (coinage,
flagged): the sub-class of the metric-facing `Σ` generated by the
interface-local attachments that live *inside* the query set `A` — the
interface is a sub-interface of `A` (`j ⊆ A`) and the engine's requests reach
only its own sub-interface (`System.RequestsWithin j E`).

The generator carries no engine class: `InnerTotal` and CR18 Definition 3.8's
uniform request bound are already recorded in the ambient
`↥converterMonoidAt`, which is what an element of this type *is*.  What the
generator adds is exactly the two support clauses that MauRen16 §3.3 and §3.4
need and that the ambient Σ does not record: where the converter is attached,
and where it reaches.

This is the `H` of `Relaxation.star`, `Relaxation.RightOutbound` and
`Relaxation.outboundHull`.  Blocks are deliberately *not* generators: `⊣` is
`Relaxation.RightOutbound`'s separate `blk` argument, not a member of the
class the resource must tolerate. -/
def converterMonoidWithin (A : Set Uni.{u}) : Submonoid ↥converterMonoidAt.{u} :=
  Submonoid.closure
    {σ : ↥converterMonoidAt.{u} |
      ∃ (j : Set Uni.{u}) (E : System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u})),
        j ⊆ A ∧ System.RequestsWithin j E ∧ (σ : Function.End Phi.{u}) = attachAt j E}

/-- An admissible attachment inside `A` is a member of the class at `A`.  The
engine class (`System.InnerTotal`, CR18 Definition 3.8's uniform bound) is what
places it in the ambient `converterMonoidAt`; the two support clauses are what
place it in the sub-class. -/
theorem attachAt_mem_converterMonoidWithin {A j : Set Uni.{u}} (hj : j ⊆ A)
    {E : System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u})}
    (hReq : System.RequestsWithin j E) (hIT : System.InnerTotal E)
    (hβ : System.AnswersWithinUniformBudget E) :
    (⟨attachAt j E, attachAt_mem_converterMonoidAt j hIT hβ⟩ : ↥converterMonoidAt.{u})
      ∈ converterMonoidWithin A :=
  Submonoid.subset_closure ⟨j, E, hj, hReq, rfl⟩

/-- The class at a larger interface is larger. -/
theorem converterMonoidWithin_mono {A A' : Set Uni.{u}} (h : A ⊆ A') :
    converterMonoidWithin A ≤ converterMonoidWithin A' := by
  refine Submonoid.closure_le.mpr ?_
  rintro σ ⟨j, E, hj, hReq, hσ⟩
  exact Submonoid.subset_closure ⟨j, E, hj.trans h, hReq, hσ⟩

/-! ## MauRen16 §3.3's `(αR)β = α(Rβ)`, class against class

Lemma 3 asks that the protocol commute with *every* member of the class `∗`
relaxes by.  On this carrier that is `attachAt_comm` — disjoint interfaces,
confined requests — lifted along the two `Submonoid.closure`s. -/

/-- One attachment inside `B` commutes with the whole class at a disjoint `A`.
The closure induction is on the class; the generator step is `attachAt_comm`,
whose `Disjoint i j` comes from `i ⊆ B`, `j ⊆ A` and `Disjoint B A`. -/
theorem coe_commute_attachAt_converterMonoidWithin {A B i : Set Uni.{u}}
    (hAB : Disjoint B A) (hiB : i ⊆ B)
    {E : System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u})}
    (hReq : System.RequestsWithin i E)
    {β : ↥converterMonoidAt.{u}} (hβ : β ∈ converterMonoidWithin A) :
    attachAt i E * (β : Function.End Phi.{u}) =
      (β : Function.End Phi.{u}) * attachAt i E := by
  induction hβ using Submonoid.closure_induction with
  | mem y hy =>
      obtain ⟨j, F, hjA, hReqF, hyF⟩ := hy
      rw [hyF]
      exact attachAt_comm (hAB.mono hiB hjA) hReq hReqF
  | one => simp
  | mul y z _ _ ihy ihz =>
      rw [Submonoid.coe_mul, ← mul_assoc, ihy, mul_assoc, ihz, ← mul_assoc]

/-- **MauRen16 §3.3's `(αR)β = α(Rβ)` between two whole classes at disjoint
interfaces**, as an equation in `Function.End Phi`.  This is the commutation
premise of Lemma 3 and Lemma 4, discharged on the carrier: no engine class is
spent, only disjointness and the two support clauses the generators carry. -/
theorem coe_commute_converterMonoidWithin {A B : Set Uni.{u}} (hAB : Disjoint B A)
    {π β : ↥converterMonoidAt.{u}} (hπ : π ∈ converterMonoidWithin B)
    (hβ : β ∈ converterMonoidWithin A) :
    (π : Function.End Phi.{u}) * (β : Function.End Phi.{u}) =
      (β : Function.End Phi.{u}) * (π : Function.End Phi.{u}) := by
  induction hπ using Submonoid.closure_induction with
  | mem x hx =>
      obtain ⟨i, E, hiB, hReqE, hxE⟩ := hx
      rw [hxE]
      exact coe_commute_attachAt_converterMonoidWithin hAB hiB hReqE hβ
  | one => simp
  | mul y z _ _ ihy ihz =>
      rw [Submonoid.coe_mul, mul_assoc, ihz, ← mul_assoc, ihy, mul_assoc]

/-- The same commutation as an equation of the metric-facing `Σ` — the form
`Relaxation.constructs_star` and `Relaxation.constructs_outboundHull`
consume. -/
theorem commute_converterMonoidWithin {A B : Set Uni.{u}} (hAB : Disjoint B A)
    {π β : ↥converterMonoidAt.{u}} (hπ : π ∈ converterMonoidWithin B)
    (hβ : β ∈ converterMonoidWithin A) : π * β = β * π :=
  Subtype.ext (coe_commute_converterMonoidWithin hAB hπ hβ)

/-! ## MauRen16 §3.4's `𝓡* := 𝓡Σ` on the carrier -/

/-- **MauRen16 §3.4's `𝓡* = 𝓡Σ` read on the carrier**: a law is in the
`∗`-relaxation exactly when some converter of the class at `A`, applied to some
law of `𝓡`, produces it.  `Relaxation.mem_star_iff` at
`Sigma := ↥converterMonoidAt`, `Φ := Phi`, with the action unfolded to what it
is here — application of an endomorphism of Φ. -/
theorem mem_star_converterMonoidWithin_iff {A : Set Uni.{u}}
    {𝓡 : Specification Phi.{u}} {L : Phi.{u}} :
    L ∈ (Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) 𝓡 ↔
      ∃ σ ∈ converterMonoidWithin A, ∃ R ∈ 𝓡, (σ : Function.End Phi.{u}) R = L :=
  Relaxation.mem_star_iff

/-- **MauRen16 eq. (1), containment half, on the carrier**: `𝓡 ⊆ 𝓡*`.  The
identity converter is in the class, so nothing is lost by relaxing. -/
theorem subset_star_converterMonoidWithin (A : Set Uni.{u}) (𝓡 : Specification Phi.{u}) :
    𝓡 ⊆ (Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) 𝓡 :=
  (Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}).le_toFun 𝓡

/-- **MauRen16 eq. (1), idempotence half, on the carrier**: `(𝓡*)* = 𝓡*`.
Two converters of the class compose to one, which is the closure `Σ∘Σ = Σ` of
§3.3 read through the relaxation. -/
theorem star_idem_converterMonoidWithin (A : Set Uni.{u}) (𝓡 : Specification Phi.{u}) :
    (Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u})
        ((Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) 𝓡) =
      (Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) 𝓡 :=
  Relaxation.star_idem _ _

/-- **MauRen16 §4.1 Lemma 3 on the carrier**: `𝓡 —π→ 𝓢 ⟹ 𝓡* —π→ 𝓢*`, for a
protocol drawn from the class at an interface disjoint from the one `∗`
relaxes by.

The paper gives no proof; the abstract one (`Relaxation.constructs_star`) is
one line of commutation, and the commutation is
`coe_commute_converterMonoidWithin` — i.e. `attachAt_comm`.  This is the
statement matrix row 37 asks for at a RandomSystems carrier. -/
theorem constructs_star_converterMonoidWithin {A B : Set Uni.{u}} (hAB : Disjoint B A)
    {π : ↥converterMonoidAt.{u}} (hπ : π ∈ converterMonoidWithin B)
    {𝓡 𝓢 : Specification Phi.{u}} (h : Constructs π 𝓡 𝓢) :
    Constructs π
      ((Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) 𝓡)
      ((Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) 𝓢) :=
  Relaxation.constructs_star (fun _ hβ => commute_converterMonoidWithin hAB hπ hβ) h

/-- **MauRen16 p. 18, unnumbered inside the proof of Theorem 2, on the
carrier**: `(𝓡ᵋ)* ⊆ (𝓡*)ᵋ`.  Relaxing by an error first and by the converter
class second is at least as weak as the other order.

The abstract statement spends `IsNonexpandingSMul` and nothing else, and that
instance is registered for `converterMonoidAt` in `MetricFullyDefined.lean`
(via `converterMonoidAt_le_nonexpandingConverters`, whose attachment generator
is `System.exists_absorb_attachEngineFully`).  So this is the carrier home
matrix row 61 was waiting on. -/
theorem star_epsilonRelaxation_subset_epsilonRelaxation_star_converterMonoidWithin
    (A : Set Uni.{u}) (ε : ℝ≥0∞) (𝓡 : Specification Phi.{u}) :
    (Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u})
        (Relaxation.epsilonRelaxation ε 𝓡) ⊆
      Relaxation.epsilonRelaxation ε
        ((Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) 𝓡) :=
  Relaxation.star_epsilonRelaxation_subset_epsilonRelaxation_star _ ε 𝓡

/-! ## MauRen16 §3.4's `⊣`, right-outboundness and `𝓡⟦` on the carrier

The blocking converter is `block A`, already a generator of the metric-facing
`Σ`.  The one thing §3.4 needs of it that the carrier did not record is that it
*commutes* with a foreign attachment, and the cheap route to that is the
identification of `⊣` with an attachment: `block A = attachAt A Z` for the
engine `Z` that never moves
(`System.attachEngineFully_eq_blockSet_of_dom_eq_empty`), whereupon `⊣`
inherits `attachAt_comm` and needs no commutation induction of its own.

The same identification puts `⊣` *inside* the class at `A`, which is what lets
the two-monoid presentation of `AbstractCryptography.Specification.Outbound`
(where `blk` must live in the right-hand monoid) instantiate here as well as
the homogeneous one of `Algebra.Star`. -/

/-- **MauRen16 §3.4's `⊣` as an element of the metric-facing `Σ`** (coinage,
flagged): the block at the query set `A`, carrying its membership.  `star`,
`RightOutbound` and `outboundHull` all take their blocking converter from the
converter monoid, so `block A` has to appear as an element of it and not only
as an endomorphism. -/
def blockConverterAt (A : Set Uni.{u}) : ↥converterMonoidAt.{u} :=
  ⟨block A, block_mem_converterMonoidAt A⟩

@[simp] theorem coe_blockConverterAt (A : Set Uni.{u}) :
    ((blockConverterAt A : ↥converterMonoidAt.{u}) : Function.End Phi.{u}) = block A := rfl

/-- **`⊣` is an interface-local attachment.**  There is an engine that never
moves, it reaches nowhere (so `System.RequestsWithin i` holds for every `i`),
and attaching it at `A` is exactly blocking `A`.

Stated existentially rather than as a named silent engine: what the §3.4
receipts consume is the *existence* of such an attachment, and naming the
engine would put a second carrier object in the registry for no mathematical
gain. -/
theorem exists_attachAt_eq_block (A : Set Uni.{u}) :
    ∃ Z : System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u}),
      System.RequestsWithin A Z ∧ attachAt A Z = block A := by
  have hvalid : System.Valid (fun _ : List (Uni.{u} ⊕ Option Uni.{u}) =>
      (Part.none : Part (Uni.{u} ⊕ Uni.{u}))) := by
    refine ⟨fun h => absurd (Part.dom_iff_mem.mp h) (by simp), ?_⟩
    intro l₁ l₂ _ _ h
    exact absurd (Part.dom_iff_mem.mp h) (by simp)
  refine ⟨⟨_, hvalid⟩, fun l x hx => absurd hx (by simp), ?_⟩
  have hZ : ∀ c, c ∉ System.dom (⟨_, hvalid⟩ :
      System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u})) := by
    intro c h
    exact absurd (Part.dom_iff_mem.mp h) (by simp)
  have h : System.attachEngineFully A (⟨_, hvalid⟩ :
      System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u})) = System.blockSet A :=
    funext fun S => System.attachEngineFully_eq_blockSet_of_dom_eq_empty hZ S
  show Distribution.fTransform (System.attachEngineFully A _) = block A
  rw [h]
  rfl

/-- `⊣` at `A` is a member of the converter class at `A` — it *is* an
attachment inside `A`.  This is what makes the two-monoid presentation of
`Specification/Outbound.lean`, where the blocking converter must live in the
right-hand monoid, instantiable on this carrier. -/
theorem blockConverterAt_mem_converterMonoidWithin (A : Set Uni.{u}) :
    blockConverterAt A ∈ converterMonoidWithin A := by
  obtain ⟨Z, hZreq, hZ⟩ := exists_attachAt_eq_block A
  exact Submonoid.subset_closure ⟨A, Z, le_rfl, hZreq, hZ.symm⟩

/-- **`⊣` commutes with a foreign attachment**: MauRen16 §3.3's `(αR)β = α(Rβ)`
with `β = ⊣`.  Blocking is an attachment (`exists_attachAt_eq_block`), so this
is `attachAt_comm` and no new induction. -/
theorem block_commute_attachAt {A i : Set Uni.{u}} (hiA : Disjoint i A)
    {E : System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u})}
    (hReq : System.RequestsWithin i E) :
    attachAt i E * block A = block A * attachAt i E := by
  obtain ⟨Z, hZreq, hZ⟩ := exists_attachAt_eq_block A
  rw [← hZ]
  exact attachAt_comm hiA hReq hZreq

/-- **`⊣` absorbs a converter attached inside it**: `⊣ α = ⊣` for `α` at a
sub-interface of the blocked set.  This is the whole content of
right-outboundness on this carrier, and it is `System`-level transparency: a
history the block admits never reaches the converter's interface. -/
theorem block_mul_attachAt_of_subset {A j : Set Uni.{u}} (hjA : j ⊆ A)
    (F : System.DDS (Uni.{u} ⊕ Option Uni.{u}) (Uni.{u} ⊕ Uni.{u})) :
    block A * attachAt j F = block A := by
  funext L
  show Distribution.fTransform (System.blockSet A)
      (Distribution.fTransform (System.attachEngineFully j F) L) = _
  rw [Distribution.fTransform_fTransform]
  exact congrFun (congrArg _ (funext fun S =>
    System.blockSet_attachEngineFully_of_subset hjA F S)) L

/-- `⊣` absorbs the *whole* class at `A`, by closure induction on the class:
the generators are absorbed one at a time and absorption is preserved by
products, since `⊣(αβ) = (⊣α)β = ⊣β = ⊣`. -/
theorem coe_block_mul_converterMonoidWithin (A : Set Uni.{u})
    {β : ↥converterMonoidAt.{u}} (hβ : β ∈ converterMonoidWithin A) :
    block A * (β : Function.End Phi.{u}) = block A := by
  induction hβ using Submonoid.closure_induction with
  | mem y hy =>
      obtain ⟨j, F, hjA, _, hyF⟩ := hy
      rw [hyF]
      exact block_mul_attachAt_of_subset hjA F
  | one => simp
  | mul y z _ _ ihy ihz => rw [Submonoid.coe_mul, ← mul_assoc, ihy, ihz]

/-- **MauRen16 §3.4's `R*⊣ = R⊣` on the carrier — and it is a theorem, not a
hypothesis.**  *Every* law of `Φ` is right-outbound with respect to the block
at `A` and the converter class at `A`: the model is query-driven, so a
converter behind a blocked interface is never activated.

MauRen16 keeps right-outboundness as a property because the abstract layer must
also serve carriers with spontaneous outputs; on this carrier, as on RS-A
(`Converter.rightOutbound_attach`), it is discharged. -/
theorem rightOutbound_blockConverterAt (A : Set Uni.{u}) (L : Phi.{u}) :
    Relaxation.RightOutbound (converterMonoidWithin A) (blockConverterAt A) L := by
  intro β hβ
  show ((blockConverterAt A * β : ↥converterMonoidAt.{u}) : Function.End Phi.{u}) L
    = ((blockConverterAt A : ↥converterMonoidAt.{u}) : Function.End Phi.{u}) L
  rw [Submonoid.coe_mul, coe_blockConverterAt, coe_block_mul_converterMonoidWithin A hβ]

/-- **MauRen16 §3.4's `𝓡⟦` on the carrier**, unfolded: the right-outbound laws
whose blocked form is a blocked law of `𝓡`. -/
theorem mem_outboundHull_blockConverterAt_iff {A : Set Uni.{u}} {𝓡 : Specification Phi.{u}}
    {L : Phi.{u}} :
    L ∈ Relaxation.outboundHull (converterMonoidWithin A) (blockConverterAt A) 𝓡 ↔
      Relaxation.RightOutbound (converterMonoidWithin A) (blockConverterAt A) L ∧
        blockConverterAt A • L ∈ (blockConverterAt A : ↥converterMonoidAt.{u}) • 𝓡 :=
  Relaxation.mem_outboundHull_iff

/-- **MauRen16 eq. (2), containment half, on the carrier — unconditionally.**
The abstract statement carries the hypothesis that every law of `𝓡` be
right-outbound, and `Relaxation.outboundHull_eq_empty_of_top` shows the
hypothesis cannot be dropped in general.  Here it is discharged for *every*
specification by `rightOutbound_blockConverterAt`, so the carrier restores the printed
form of eq. (2). -/
theorem subset_outboundHull_blockConverterAt (A : Set Uni.{u}) (𝓡 : Specification Phi.{u}) :
    𝓡 ⊆ Relaxation.outboundHull (converterMonoidWithin A) (blockConverterAt A) 𝓡 :=
  Relaxation.subset_outboundHull _ _ fun L _ => rightOutbound_blockConverterAt A L

/-- **MauRen16 eq. (2), idempotence half, on the carrier**: `(𝓡⟦)⟦ = 𝓡⟦`. -/
theorem outboundHull_idem_blockConverterAt (A : Set Uni.{u}) (𝓡 : Specification Phi.{u}) :
    Relaxation.outboundHull (converterMonoidWithin A) (blockConverterAt A)
        (Relaxation.outboundHull (converterMonoidWithin A) (blockConverterAt A) 𝓡) =
      Relaxation.outboundHull (converterMonoidWithin A) (blockConverterAt A) 𝓡 :=
  Relaxation.outboundHull_idem _ _ _

/-- `⊣` commutes with the whole honest class at a disjoint interface — the
second commutation premise of Lemma 4, by closure induction off
`block_commute_attachAt`. -/
theorem coe_commute_block_converterMonoidWithin {A B : Set Uni.{u}} (hAB : Disjoint B A)
    {π : ↥converterMonoidAt.{u}} (hπ : π ∈ converterMonoidWithin B) :
    (π : Function.End Phi.{u}) * block A = block A * (π : Function.End Phi.{u}) := by
  induction hπ using Submonoid.closure_induction with
  | mem x hx =>
      obtain ⟨i, E, hiB, hReq, hxE⟩ := hx
      rw [hxE]
      exact block_commute_attachAt (hAB.mono hiB le_rfl) hReq
  | one => simp
  | mul y z _ _ ihy ihz =>
      rw [Submonoid.coe_mul, mul_assoc, ihz, ← mul_assoc, ihy, mul_assoc]

/-- The same, as an equation of the metric-facing `Σ`. -/
theorem commute_blockConverterAt {A B : Set Uni.{u}} (hAB : Disjoint B A)
    {π : ↥converterMonoidAt.{u}} (hπ : π ∈ converterMonoidWithin B) :
    π * blockConverterAt A = blockConverterAt A * π :=
  Subtype.ext (coe_commute_block_converterMonoidWithin hAB hπ)

/-- **MauRen16 §4.1 Lemma 4 on the carrier**: `𝓡 —π→ 𝓢 ⟹ 𝓡⟦ —π→ 𝓢⟦`, for a
protocol drawn from the class at an interface disjoint from the blocked one.

The paper gives no proof; the abstract one spends two commutations — with the
class and with `⊣` — and both are `attachAt_comm` here.  This is the statement
matrix row 38 had only at the metric-free carrier RS-A. -/
theorem constructs_outboundHull_converterMonoidWithin {A B : Set Uni.{u}}
    (hAB : Disjoint B A) {π : ↥converterMonoidAt.{u}} (hπ : π ∈ converterMonoidWithin B)
    {𝓡 𝓢 : Specification Phi.{u}} (h : Constructs π 𝓡 𝓢) :
    Constructs π
      (Relaxation.outboundHull (converterMonoidWithin A) (blockConverterAt A) 𝓡)
      (Relaxation.outboundHull (converterMonoidWithin A) (blockConverterAt A) 𝓢) :=
  Relaxation.constructs_outboundHull
    (fun _ hβ => commute_converterMonoidWithin hAB hπ hβ) (commute_blockConverterAt hAB hπ) h

/-! ### The two-monoid presentation, instantiated as well

`Specification/Outbound.lean` renders §3.4 with left and right attachment as
*distinct* monoids `SigmaL`, `SigmaR` mapped into the ambient one by homs
`eL`, `eR`.  That presentation does not resist this carrier: the two classes
`converterMonoidWithin B` and `converterMonoidWithin A` are the two monoids,
their `Submonoid.subtype`s are the two homs, and `OrderInvariant` is
`commute_converterMonoidWithin` read pointwise.  The one thing it needs beyond
the homogeneous rendering is `blk : SigmaR`, i.e. that `⊣` lie in the *right*
class — which is `blockConverterAt_mem_converterMonoidWithin`. -/

/-- MR16 §3.3's `(αR)β = α(Rβ)` in the two-monoid form `Outbound.lean` asks
for. -/
theorem orderInvariant_converterMonoidWithin {A B : Set Uni.{u}} (hAB : Disjoint B A) :
    AbstractCryptography.OrderInvariant Phi.{u}
      (converterMonoidWithin B).subtype (converterMonoidWithin A).subtype := by
  intro α β L
  show ((α : ↥converterMonoidAt.{u}) : Function.End Phi.{u})
      (((β : ↥converterMonoidAt.{u}) : Function.End Phi.{u}) L) = _
  exact congrFun (coe_commute_converterMonoidWithin hAB α.2 β.2) L

/-- Right-outboundness in the two-monoid form. -/
theorem rightOutbound_subtype (A : Set Uni.{u}) (L : Phi.{u}) :
    AbstractCryptography.RightOutbound (converterMonoidWithin A).subtype
      ⟨blockConverterAt A, blockConverterAt_mem_converterMonoidWithin A⟩ L := by
  intro β
  show (block A) (((β : ↥converterMonoidAt.{u}) : Function.End Phi.{u}) L) = (block A) L
  exact congrFun (coe_block_mul_converterMonoidWithin A β.2) L

/-- **Lemma 4 in the two-monoid form** — the receipt RS-A carries
(`RandomSystemsReceipts.lean` §4), now on the metric carrier. -/
theorem constructs_outboundCompatible_converterMonoidWithin {A B : Set Uni.{u}}
    (hAB : Disjoint B A) (blk : ↥(converterMonoidWithin A))
    {π : ↥(converterMonoidWithin B)} {𝓡 𝓢 : Specification Phi.{u}}
    (h : Constructs ((converterMonoidWithin B).subtype π) 𝓡 𝓢) :
    Constructs ((converterMonoidWithin B).subtype π)
      (AbstractCryptography.outboundCompatible (converterMonoidWithin A).subtype blk 𝓡)
      (AbstractCryptography.outboundCompatible (converterMonoidWithin A).subtype blk 𝓢) :=
  AbstractCryptography.Constructs.outboundCompatible _ blk
    (orderInvariant_converterMonoidWithin hAB) h

/-! ## MauRen16 §4.2 — indifferentiability as a construction, on the carrier

Everything above is converter algebra; §4.2 is where the distance enters.  The
`PseudoEMetricSpace Phi` instance and the `IsNonexpandingSMul` instance at
`converterMonoidAt` are `MetricFullyDefined.lean`'s, so MauRen11 Definition 23
and MauRen16 Lemma 5 land here with the `∗`-relaxation supplied by this file.

The endpoint is the last statement of the section: a simulator-based step and
an ordinary approximate construction compose into one construction into the
`ε`-relaxed `∗`-relaxation.  It is Lemma 5 followed by Lemma 3, the ε/∗
interchange, and Lemma 1∘2 — every §4 ingredient at once, at one carrier. -/

/-- **MauRen16 §4.2 eq. (3) on the carrier**: `πR ≈ᵋ Sσ`, with the simulator
drawn from the converter class at the adversary interface `A`, and the
distance the fully defined carrier's own. -/
theorem indifferentiable_iff_at {A : Set Uni.{u}} {ε : ℝ≥0∞} {R S : Phi.{u}} :
    AbstractCryptography.Indifferentiable (converterMonoidWithin A) ε R S ↔
      ∃ π : ↥converterMonoidAt.{u}, ∃ σ ∈ converterMonoidWithin A,
        edist ((π : Function.End Phi.{u}) R) ((σ : Function.End Phi.{u}) S) ≤ ε :=
  Iff.rfl

/-- **MauRen16 §4.2 Lemma 5 on the carrier, explicit-witness form**: a
simulator `σ` in the class at `A` with `πR ≈ᵋ Sσ` *is* the construction
statement `R —π→ (S*)ᵋ`.

No non-expansion is spent — the membership `σS ∈ S∗` and one triangle-free
distance bound are the whole proof — which is why this fires at any `π` of the
metric-facing Σ, honest class or not. -/
theorem constructs_star_epsilonRelaxation_of_simulator_at {A : Set Uni.{u}}
    {π σ : ↥converterMonoidAt.{u}} (hσ : σ ∈ converterMonoidWithin A)
    {R S : Phi.{u}} {ε : ℝ≥0∞} (h : edist (π • R) (σ • S) ≤ ε) :
    ({R} : Specification Phi.{u}) —[π]→
      Relaxation.epsilonRelaxation ε
        ((Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) {S}) :=
  AbstractCryptography.constructs_of_simulator σ hσ h

/-- **MauRen11 App. D Definition 23 turned into a construction statement, on
the carrier** — MauRen16 §4.2's reading of indifferentiability: `T`
indifferentiable from `S` within `ε` means `T ⊆ (S∗)ᵋ`, and at `T = πR` that is
`R —π→ (S∗)ᵋ`.  The protocol witness the definition hides is re-exported. -/
theorem indifferentiable_construct_at {A : Set Uni.{u}} {ε : ℝ≥0∞} {R S : Phi.{u}}
    (h : AbstractCryptography.Indifferentiable (converterMonoidWithin A) ε R S) :
    ∃ π : ↥converterMonoidAt.{u}, ({R} : Specification Phi.{u}) —[π]→
      Relaxation.epsilonRelaxation ε
        ((Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) {S}) :=
  h.construct

/-- **The indifferentiability endpoint on the fully defined carrier.**

A simulator-based step at the adversary interface `A` — MauRen16 eq. (3),
`πR ≈ᵋ Sσ` with `σ` admitted — followed by an ordinary approximate
construction `S —π′→ Tᵋ′` with `π′` an honest protocol at an interface
disjoint from `A`, is one construction

  `R —π′∘π→ ((T∗)^{ε+ε′})`.

Four §4 facts, all of them at this carrier and none of them re-proved here:

* **Lemma 5** (`constructs_star_epsilonRelaxation_of_simulator_at`) turns the
  simulator step into `R —π→ (S∗)ᵋ`;
* **Lemma 3** (`constructs_star_converterMonoidWithin`) carries the second leg
  through the `∗`, on the commutation `attachAt_comm` supplies;
* the **ε/∗ interchange** `(𝓡ᵋ)∗ ⊆ (𝓡∗)ᵋ` (matrix row 61) pushes the second
  leg's error back out through the `∗`;
* **Lemma 1 composed with Lemma 2** (`Constructs.epsilonRelaxation_trans`,
  which the registered `IsNonexpandingSMul` instance fires) adds the errors.

This is deliberately *not* `AbstractCryptography.Indifferentiable.trans`.  That
theorem's premise centralizes the simulator class in the **whole** ambient
monoid, and on this carrier that is false: an attachment at an interface
meeting `A` need not commute with a converter at `A`.  Fixing the second
protocol inside a class disjoint from `A` is the honest carrier form, and it is
what MauRen16 §7's honest/dishonest grouping gives anyway. -/
theorem constructs_star_epsilonRelaxation_trans_at {A B : Set Uni.{u}}
    (hAB : Disjoint B A) {π π' σ : ↥converterMonoidAt.{u}}
    (hπ' : π' ∈ converterMonoidWithin B) (hσ : σ ∈ converterMonoidWithin A)
    {R S T : Phi.{u}} {ε ε' : ℝ≥0∞}
    (h : edist (π • R) (σ • S) ≤ ε) (h' : edist (π' • S) T ≤ ε') :
    ({R} : Specification Phi.{u}) —[π' * π]→
      Relaxation.epsilonRelaxation (ε + ε')
        ((Relaxation.star (converterMonoidWithin A) : Relaxation Phi.{u}) {T}) :=
  AbstractCryptography.Constructs.epsilonRelaxation_trans
    (constructs_star_epsilonRelaxation_of_simulator_at hσ h)
    (Constructs.mono subset_rfl
      (star_epsilonRelaxation_subset_epsilonRelaxation_star_converterMonoidWithin A ε' {T})
      (constructs_star_converterMonoidWithin hAB hπ'
        (AbstractCryptography.constructs_singleton_epsilonRelaxation_iff.mpr h')))

end

end RandomSystems
