/-
Copyright (c) 2026 Trail of Bits. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Informalization.MassotMiller.InfoTree

/-!
# Proof-term decompilation for the Massot–Miller explainer

The tactic describers use source tactics when those tactics expose the proof
structure.  Term-bearing and opaque tactics instead enter here.  The input is
exactly the triple described in the talks: local context, expected type, and
kernel proof term.  The output is a synthesized tactic tree whose nodes retain
their intermediate goals.
-/

namespace Informalization.MassotMiller.Decompiler

open Lean Meta
open Informalization.MassotMiller.InfoTree

/-- The small semantic tactic vocabulary synthesized from kernel terms. -/
inductive StepKind where
  | intro (name : Name) (domain : Expr)
  | letBinding (name : Name) (type value : Expr)
  | constructor (name : Option Name)
  | existsWitness (witness : Expr)
  | chooseLeft
  | chooseRight
  | assumption (name : Name)
  | projection (index : Nat)
  | apply (reference : Expr)
  | exact (reference : Expr)
  | reflexivity
  | contradiction
  | cases (recursor : Name)
  | rewrite (principle : Name)
  | whnf (before after : Expr)
  | opaque

/-- An exact synthesized proof state. -/
structure SyntheticGoal where
  localContext : LocalContext
  target : Expr

/-- A proof-term-derived tactic node and the subgoals generated by it. -/
inductive SyntheticTactic where
  | node
      (kind : StepKind)
      (goal : SyntheticGoal)
      (proofTerm : Expr)
      (children : Array SyntheticTactic)

namespace SyntheticTactic

def kind : SyntheticTactic → StepKind
  | .node kind .. => kind

def goal : SyntheticTactic → SyntheticGoal
  | .node _ goal .. => goal

def proofTerm : SyntheticTactic → Expr
  | .node _ _ proofTerm _ => proofTerm

def children : SyntheticTactic → Array SyntheticTactic
  | .node _ _ _ children => children

end SyntheticTactic

/-- One checked relation in a `calc` chain. -/
structure SyntheticCalcStep where
  relation : Expr
  rhs : Expr
  proof : SyntheticTactic

/-- A kernel-recovered calculation, independent of tactic child-goal layout. -/
structure SyntheticCalculation where
  goal : SyntheticGoal
  start : Expr
  steps : Array SyntheticCalcStep

def headConstant? (term : Expr) : Option Name :=
  match term.getAppFn.consumeMData with
  | .const name _ => some name
  | _ => none

private def headReference (term : Expr) : Expr := term.getAppFn.consumeMData

private def isRecursorName (name : Name) : Bool :=
  let text := name.toString
  text.endsWith ".rec" || text.endsWith ".recOn" ||
    text.endsWith ".casesOn" || text.endsWith ".brecOn"

private def currentGoal (target : Expr) : MetaM SyntheticGoal := do
  return { localContext := ← getLCtx, target }

/-- Arguments which are themselves proofs.  Type and instance parameters are
not guessed from syntax: Lean's elaborated type of each argument decides. -/
private def proofArguments (term : Expr) : MetaM (Array (Expr × Expr)) := do
  let mut result := #[]
  for argument in term.getAppArgs do
    try
      let type ← inferType argument
      if ← isProp type then
        result := result.push (argument, type)
    catch _ => pure ()
  return result

/-- Decompile one kernel term.  `fuel` bounds unfolding and malformed/cyclic
metavariable data while leaving ordinary proof-tree depth unrestricted in
practice. -/
partial def decompileAux (expected proofTerm : Expr) (fuel : Nat := 256) :
    MetaM SyntheticTactic := do
  let expected ← instantiateMVars expected
  let proofTerm ← instantiateMVars proofTerm
  let goal ← currentGoal expected
  if fuel == 0 then
    return .node .opaque goal proofTerm #[]

  let expectedWhnf ← whnf expected
  if expectedWhnf != expected then
    let child ← decompileAux expectedWhnf proofTerm (fuel - 1)
    return .node (.whnf expected expectedWhnf) goal proofTerm #[child]

  match expectedWhnf with
  | .forallE name domain body binderInfo =>
      withLocalDecl name binderInfo domain fun localVar => do
        let body := body.instantiate1 localVar
        let applied ← whnf (mkApp proofTerm localVar)
        let child ← decompileAux body applied (fuel - 1)
        return .node (.intro name domain) goal proofTerm #[child]
  | _ =>
    match proofTerm with
    | .mdata _ inner => decompileAux expected inner (fuel - 1)
    | .letE name type value body _ =>
        withLetDecl name type value fun localVar => do
          let child ← decompileAux expected (body.instantiate1 localVar) (fuel - 1)
          return .node (.letBinding name type value) goal proofTerm #[child]
    | .fvar id =>
        let declaration ← id.getDecl
        return .node (.assumption declaration.userName) goal proofTerm #[]
    | .proj _ index source =>
        let sourceType ← inferType source
        let child ← decompileAux sourceType source (fuel - 1)
        return .node (.projection index) goal proofTerm #[child]
    | .app .. =>
        let function := proofTerm.getAppFn.consumeMData
        if function.isLambda || function.isLet then
          let reduced ← whnf proofTerm
          if reduced != proofTerm then
            let child ← decompileAux expected reduced (fuel - 1)
            return .node (.whnf proofTerm reduced) goal proofTerm #[child]
        let headName? := headConstant? proofTerm
        let arguments := proofTerm.getAppArgs
        let proofArgs ← proofArguments proofTerm
        let mut children := #[]
        for (argumentProof, argumentType) in proofArgs do
          children := children.push (← decompileAux argumentType argumentProof (fuel - 1))
        match headName? with
        | some name =>
            if name == ``Eq.refl then
              return .node .reflexivity goal proofTerm #[]
            else if name == ``And.intro || name == ``Iff.intro then
              return .node (.constructor (some name)) goal proofTerm children
            else if name == ``Exists.intro then
              let witness := arguments[arguments.size - 2]?.getD proofTerm
              return .node (.existsWitness witness) goal proofTerm children
            else if name == ``Or.inl then
              return .node .chooseLeft goal proofTerm children
            else if name == ``Or.inr then
              return .node .chooseRight goal proofTerm children
            else if name == ``False.elim then
              return .node .contradiction goal proofTerm children
            else if name == ``Eq.mp || name == ``Eq.mpr || name == ``Eq.ndrec ||
                name == ``Eq.rec then
              return .node (.rewrite name) goal proofTerm children
            else if isRecursorName name then
              return .node (.cases name) goal proofTerm children
            else if children.isEmpty then
              return .node (.exact (headReference proofTerm)) goal proofTerm #[]
            else
              return .node (.apply (headReference proofTerm)) goal proofTerm children
        | none =>
            if children.isEmpty then
              return .node (.exact function) goal proofTerm #[]
            else
              return .node (.apply function) goal proofTerm children
    | .const name _ =>
        if name == ``Eq.refl then
          return .node .reflexivity goal proofTerm #[]
        return .node (.exact proofTerm) goal proofTerm #[]
    | _ => return .node (.exact proofTerm) goal proofTerm #[]

/-- Recover the chain built by Lean's `calc` elaborator.  Lean composes
successive relation proofs with `Trans.trans`; following that checked term is
more reliable than expecting each source step to create a tactic goal. -/
private partial def decompileCalculationAux (expected proofTerm : Expr)
    (fuel : Nat := 256) : MetaM (Option (Expr × Array SyntheticCalcStep)) := do
  if fuel == 0 then return none
  let expected ← instantiateMVars expected
  let proofTerm ← instantiateMVars proofTerm
  let some (relation, lhs, rhs) ← Lean.Elab.Term.getCalcRelation? expected | return none
  if headConstant? proofTerm == some ``Trans.trans then
    let arguments := proofTerm.getAppArgs
    let some leftProof := arguments[arguments.size - 2]? | return none
    let some rightProof := arguments[arguments.size - 1]? | return none
    let leftType ← inferType leftProof
    let rightType ← inferType rightProof
    let some (_, leftSteps) ← decompileCalculationAux leftType leftProof (fuel - 1)
      | return none
    let some (rightRelation, _, rightRhs) ←
        Lean.Elab.Term.getCalcRelation? (← instantiateMVars rightType) | return none
    let rightTree ← decompileAux rightType rightProof (fuel - 1)
    return some (lhs, leftSteps.push {
      relation := rightRelation
      rhs := rightRhs
      proof := rightTree
    })
  let proof ← decompileAux expected proofTerm (fuel - 1)
  return some (lhs, #[{ relation, rhs, proof }])

/-- Recover a source `calc` from the exact proof assigned to its goal. -/
def calculationFromEvent (event : TacticEvent) : IO (Option SyntheticCalculation) := do
  let some target := event.target | return none
  let some proofTerm := event.proofTerm? | return none
  let context := { event.source.context with mctx := event.source.info.mctxAfter }
  context.runMetaM {} do
    target.withContext do
      let declaration ← target.getDecl
      let some (start, steps) ← decompileCalculationAux declaration.type proofTerm
        | return none
      return some {
        goal := { localContext := declaration.lctx, target := declaration.type }
        start
        steps
      }

/-- Run the decompiler in the precise post-tactic metavariable context. -/
def fromEvent (event : TacticEvent) : IO (Option SyntheticTactic) := do
  let some target := event.target | return none
  let some proofTerm := event.proofTerm? | return none
  let context := { event.source.context with mctx := event.source.info.mctxAfter }
  context.runMetaM {} do
    target.withContext do
      let declaration ← target.getDecl
      return some (← decompileAux declaration.type proofTerm)

/-- Decompile the kernel value of an entire declaration.  This is the frontend
path for term-style theorems, whose `InfoTree` legitimately has no
`TacticInfo`.  The elaboration context supplies the exact environment; the
declaration's closed type and value then reconstruct all introduced locals and
intermediate goals. -/
def fromDeclaration (context : Elab.ContextInfo) (name : Name) :
    IO (Option SyntheticTactic) :=
  context.runMetaM {} do
    let information ← getConstInfo name
    let some proofTerm := information.value? (allowOpaque := true)
      | return none
    withLCtx {} #[] do
      return some (← decompileAux information.type proofTerm)

end Informalization.MassotMiller.Decompiler
