import ConstructiveCryptography.DSL
import ConstructiveCryptography.Notation
import Mathlib.Data.ZMod.Basic

/-!
# The computational Diffie–Hellman assumption

Let `G` be a cyclic group of order `q` generated by `g`. Given `g^α` and `g^β` for uniform
`α, β ∈ ℤ_q`, computing `g^{αβ}` is hard (Boneh–Shoup, Chapter 10). As a pair of systems on one
interface, both give the challenge `(g^α, g^β)`: the real system answers each guess by whether
it is `g^{αβ}`, and the ideal system rejects every guess. The assumption is that the real system
substitutes for the ideal one within an error.

## Main definitions

* `CDH G`: the interface, with the ports `challenge` and `check`
* `CDH.Real q g`, `CDH.Ideal q g`: the real and the ideal system
* `CDH.Assumption.systems q g budget`: the pair of the real and the ideal system
* `CDH.Assumption q g error`: the real system substitutes for the ideal one within
  `error` against the admitted distinguishers
-/

namespace Commons

open SystemAlgebra SystemAlgebra.DSL
open scoped SystemAlgebra SystemAlgebra.DSL

interface CDH(G : Type) [Fintype G]
  challenge() → G × G
  check(guess : G) → Bool

variable {G : Type} [Group G] [Fintype G]

-- `(g^α, g^β)` for uniform `α, β ∈ ℤ_q`; each guess is checked against `g^{αβ}`.
system CDH.Real(q : ℕ) [NeZero q] (g : G) [DecidableEq G] : CDH G
  initialize
    α ←$ 𝒰[ZMod q]
    β ←$ 𝒰[ZMod q]
  on challenge() → G × G
    return (g ^ ZMod.val α, g ^ ZMod.val β)
  on check(guess : G) → Bool
    return decide (guess = g ^ ZMod.val (α * β))

-- The same challenge; every guess is rejected.
system CDH.Ideal(q : ℕ) [NeZero q] (g : G) : CDH G
  initialize
    α ←$ 𝒰[ZMod q]
    β ←$ 𝒰[ZMod q]
  on challenge() → G × G
    return (g ^ ZMod.val α, g ^ ZMod.val β)
  on check(_guess : G) → Bool
    return false

/-- **The systems of the CDH assumption**: the real and the ideal system, at the budget
`budget`. -/
noncomputable def CDH.Assumption.systems (q : ℕ) [NeZero q] (g : G) [DecidableEq G] (budget : ℕ) :
    Interface.Resource (CDH G budget) × Interface.Resource (CDH G budget) :=
  (CDH.Real q g, CDH.Ideal q g)

/-- **The CDH assumption** within `error`: against the admitted distinguishers, the real system
substitutes for the ideal one. -/
def CDH.Assumption [Interface.AdmissibleDistinguishers] (q : ℕ)
    [NeZero q] (g : G) [DecidableEq G] {budget : ℕ}
    (error : (CDH G budget).inputDomain.Distinguisher → ENNReal) : Prop :=
  (CDH.Assumption.systems q g budget).1 ≃[error] (CDH.Assumption.systems q g budget).2

end Commons
