import ConstructiveCryptography.Substitution.Basic

set_option autoImplicit false

/-!
# Operations on implication witnesses

Implication witnesses are closed under replacing the endpoints by equal systems,
reindexing the assumptions, a single use of one assumption, transformation by a converter,
reversal and concatenation, with the use counts tracked. A target is derivable when some
witness of at least one step exists; derivability is the substitution relation generated by
the assumptions.

## Main definitions

* `Implication.withEndpoints`, `Implication.reindex`, `Implication.single`,
  `Implication.map`, `Implication.reverse`, `Implication.append`
* `SubstitutionRelation.derivable`, `SubstitutionRelation.generatedRelation`

## Main results

* `Implication.usageCount_append` and the use counts of the other operations
* `SubstitutionRelation.derivable_substitutes`: a derivable substitution holds in every
  substitution relation satisfying the assumptions

Source: Banfi 2023, §2.3.1.
-/

namespace ConstructiveCryptography.CryptographicAlgebra.SubstitutionRelation

open CategoryTheory
open scoped BigOperators

universe u v w x y

variable {C : Type u} [Category.{v} C]
variable {Phi : C → Type w} [ResourceTheory C Phi]
variable {ι : Type x} {boundary : ι → C}
variable {systems : ∀ i, Bool → Phi (boundary i)}

namespace Implication

/-- Replace the displayed endpoints using supplied exact equalities.

Banfi, Section 2.3.1 (printed pp. 14--15): "Y₀ ≡ ρ₁(Xᵢ₁,b₁)".
Only the endpoint descriptions change; every assumption use is retained. -/
def withEndpoints {target : C} {uses : Nat}
    (implication : Implication boundary systems target uses)
    (left right : Phi target)
    (left_eq : left = implication.targetLeft)
    (right_eq : right = implication.targetRight) :
    Implication boundary systems target uses :=
  { implication with
    targetLeft := left
    targetRight := right
    start_eq := left_eq.trans implication.start_eq
    end_eq := right_eq.trans implication.end_eq }

/-- Exact endpoint replacement does not use an assumption.
Banfi, Section 2.3.1 (printed p. 14): "the number of times each substitution". -/
theorem usageCount_withEndpoints [DecidableEq ι] {target : C} {uses : Nat}
    (implication : Implication boundary systems target uses)
    (left right : Phi target)
    (left_eq : left = implication.targetLeft)
    (right_eq : right = implication.targetRight) (assumption : ι) :
    (implication.withEndpoints left right left_eq right_eq).usageCount assumption =
      implication.usageCount assumption := rfl

/-- Regard the same implication as using assumptions from a larger named
family. Only the assumption indices change.

Banfi, Theorem 2.4.4 (printed pp. 28--29), combines the two lists
"`s₁,₁, s₁,₂, ..., s₂,₁, s₂,₂, ...`". Mapping their indices into the
combined family preserves the systems, directions, transformations, and
exact joins; it does not choose any new premise. -/
def reindex {κ : Type y} {largerBoundary : κ → C}
    {largerSystems : ∀ i, Bool → Phi (largerBoundary i)}
    (inclusion : ι → κ) {target : C} {uses : Nat}
    (implication : Implication (fun i => largerBoundary (inclusion i))
      (fun i => largerSystems (inclusion i)) target uses) :
    Implication largerBoundary largerSystems target uses where
  targetLeft := implication.targetLeft
  targetRight := implication.targetRight
  index := fun position => inclusion (implication.index position)
  direction := implication.direction
  transformation := implication.transformation
  start_eq := implication.start_eq
  link_eq := implication.link_eq
  end_eq := implication.end_eq

/-- One transformed assumption is a one-position implication witness.

Banfi, Section 2.3.1 (printed p. 14), uses the endpoint equation
"`Y₀ ≡ ρ₁(Xᵢ₁,b₁)`" and its corresponding final equation. -/
def single {target : C} (assumption : ι) (direction : Bool)
    (transformation : target ⟶ boundary assumption) :
    Implication boundary systems target 0 where
  targetLeft := attach transformation (systems assumption direction)
  targetRight := attach transformation (systems assumption (!direction))
  index := fun _ => assumption
  direction := fun _ => direction
  transformation := fun _ => transformation
  start_eq := rfl
  link_eq := fun position => Fin.elim0 position
  end_eq := rfl

/-- A one-position implication uses exactly its selected assumption once.
Banfi, Section 2.3.1 (printed p. 14): "the number of times each substitution".
The sole position is counted precisely when its assumption index matches. -/
theorem usageCount_single [DecidableEq ι] {target : C}
    (selected assumption : ι) (direction : Bool)
    (transformation : target ⟶ boundary selected) :
    (single (systems := systems) selected direction transformation).usageCount assumption =
      if selected = assumption then 1 else 0 := by
  -- The sole position contributes precisely when its premise index matches.
  change (Finset.univ.filter (fun _ : Fin 1 => selected = assumption)).card = _
  rw [Finset.filter_const]
  split_ifs
  · exact Finset.card_univ.trans (Fintype.card_fin 1)
  · rfl

/-- Attach a converter to every transformed system in an implication.

Banfi, Definition 2.3.1 (printed p. 13): "Preservation: `S ≃ T ⇒ ρ(S) ≃ ρ(T)`".
The categorical attachment law composes each named transformation, while
leaving every assumption index and direction unchanged. -/
def map {source target : C} {uses : Nat}
    (implication : Implication boundary systems source uses)
    (converter : target ⟶ source) : Implication boundary systems target uses where
  targetLeft := attach converter implication.targetLeft
  targetRight := attach converter implication.targetRight
  index := implication.index
  direction := implication.direction
  transformation := fun position => converter ≫ implication.transformation position
  start_eq := by
    -- The first endpoint is transformed by the same outer converter.
    rw [implication.start_eq, attach_serial]
  link_eq := fun position => by
    -- Apply the outer converter to each exact intermediate equality.
    rw [attach_serial, attach_serial, implication.link_eq position]
  end_eq := by
    -- The final endpoint has the same serial-attachment equation.
    rw [implication.end_eq, attach_serial]

/-- Transforming a chain does not change the number of uses of an assumption.
Banfi, Section 2.3.1 (printed p. 14): "the number of times each substitution".
Only the named transformations change, not the index function being counted. -/
theorem usageCount_map [DecidableEq ι] {source target : C} {uses : Nat}
    (implication : Implication boundary systems source uses)
    (converter : target ⟶ source) (assumption : ι) :
    (implication.map converter).usageCount assumption = implication.usageCount assumption :=
  rfl

/-- Reverse a finite implication, reversing positions and every direction bit.

Banfi, Definition 2.3.1 (printed p. 13): "Symmetry: `S ≃ T ⇔ T ≃ S`".
Exact intermediate equalities are reversed with the chain. -/
def reverse {target : C} {uses : Nat}
    (implication : Implication boundary systems target uses) :
    Implication boundary systems target uses where
  targetLeft := implication.targetRight
  targetRight := implication.targetLeft
  index := fun position => implication.index position.rev
  direction := fun position => !(implication.direction position.rev)
  transformation := fun position => implication.transformation position.rev
  start_eq := by
    -- The former final right side becomes the first left side.
    exact implication.end_eq.trans (congrArg (fun position =>
      attach (implication.transformation position)
        (systems (implication.index position) (!(implication.direction position))))
      (Fin.rev_zero uses).symm)
  link_eq := fun position => by
    -- Swap adjacent positions and both sides of their old exact join.
    simpa only [Bool.not_not] using
      (congrArg (fun index => attach (implication.transformation index)
        (systems (implication.index index) (implication.direction index)))
        (Fin.rev_castSucc position)).trans
          ((implication.link_eq position.rev).symm.trans
            (congrArg (fun index => attach (implication.transformation index)
              (systems (implication.index index) (!(implication.direction index))))
              (Fin.rev_succ position).symm))
  end_eq := by
    -- The former initial left side becomes the final right side.
    simpa only [Bool.not_not] using implication.start_eq.trans
      (congrArg (fun position => attach (implication.transformation position)
        (systems (implication.index position) (implication.direction position)))
        (Fin.rev_last uses).symm)

/-- Reversing a chain preserves each assumption's use count.
Banfi, Section 2.3.1 (printed p. 14): "`tⱼ := |{k | iₖ = j, k ∈ [n]}|`".
Reversal is a permutation of those positions. -/
theorem usageCount_reverse [DecidableEq ι] {target : C} {uses : Nat}
    (implication : Implication boundary systems target uses) (assumption : ι) :
    implication.reverse.usageCount assumption = implication.usageCount assumption := by
  -- Count positions by their indicator, and reindex by the reversal permutation.
  unfold usageCount
  simp only [Finset.card_eq_sum_ones, Finset.sum_filter]
  exact Equiv.sum_comp Fin.revPerm (fun position =>
    if implication.index position = assumption then (1 : Nat) else 0)

/-- Concatenate two implication witnesses at one explicitly equal middle.

Banfi, Section 2.3.1 (printed pp. 14--15):
"`ρⱼ(Xᵢⱼ,1−bⱼ) ≡ ρⱼ₊₁(Xᵢⱼ₊₁,bⱼ₊₁)`". The new boundary join is exactly
the first witness's final equation, the supplied middle equality, and the
second witness's initial equation. No assumption is merged or dropped. -/
def append {target : C} {firstUses secondUses : Nat}
    (first : Implication boundary systems target firstUses)
    (second : Implication boundary systems target secondUses)
    (join : first.targetRight = second.targetLeft) :
    Implication boundary systems target ((firstUses + 1) + secondUses) := by
  let entries : Fin ((firstUses + 1) + (secondUses + 1)) →
      (Σ assumption : ι, Bool × (target ⟶ boundary assumption)) :=
    Fin.addCases
      (fun position => ⟨first.index position, first.direction position,
        first.transformation position⟩)
      (fun position => ⟨second.index position, second.direction position,
        second.transformation position⟩)
  let initial (entry : Σ assumption : ι, Bool × (target ⟶ boundary assumption)) :=
    attach entry.2.2 (systems entry.1 entry.2.1)
  let final (entry : Σ assumption : ι, Bool × (target ⟶ boundary assumption)) :=
    attach entry.2.2 (systems entry.1 (!entry.2.1))
  have firstEntry (position : Fin (firstUses + 1)) :
      entries (position.castAdd (secondUses + 1)) =
        ⟨first.index position, first.direction position, first.transformation position⟩ :=
    Fin.addCases_left position
  have secondEntry (position : Fin (secondUses + 1)) :
      entries (Fin.natAdd (firstUses + 1) position) =
        ⟨second.index position, second.direction position, second.transformation position⟩ :=
    Fin.addCases_right position
  refine {
    targetLeft := first.targetLeft
    targetRight := second.targetRight
    index := fun position => (entries position).1
    direction := fun position => (entries position).2.1
    transformation := fun position => (entries position).2.2
    start_eq := ?_
    link_eq := ?_
    end_eq := ?_ }
  · -- The concatenation begins at the first witness's initial position.
    change first.targetLeft = initial
      (entries ((0 : Fin (firstUses + 1)).castAdd (secondUses + 1)))
    exact first.start_eq.trans (congrArg initial (firstEntry 0)).symm
  · intro position
    -- A join lies inside the first chain, at its boundary, or inside the second.
    refine Fin.addCases (m := firstUses + 1) (n := secondUses) ?_ ?_ position
    · intro firstPosition
      refine Fin.lastCases ?_ (fun earlier => ?_) firstPosition
      · change final (entries ((Fin.last firstUses).castAdd (secondUses + 1))) =
          initial (entries (Fin.natAdd (firstUses + 1) 0))
        exact (congrArg final (firstEntry (Fin.last firstUses))).trans
          (first.end_eq.symm.trans (join.trans (second.start_eq.trans
            (congrArg initial (secondEntry 0)).symm)))
      · change final (entries (earlier.castSucc.castAdd (secondUses + 1))) =
          initial (entries (earlier.succ.castAdd (secondUses + 1)))
        exact (congrArg final (firstEntry earlier.castSucc)).trans
          ((first.link_eq earlier).trans
            (congrArg initial (firstEntry earlier.succ)).symm)
    · intro secondPosition
      change final (entries (Fin.natAdd (firstUses + 1) secondPosition.castSucc)) =
        initial (entries (Fin.natAdd (firstUses + 1) secondPosition.succ))
      exact (congrArg final (secondEntry secondPosition.castSucc)).trans
        ((second.link_eq secondPosition).trans
          (congrArg initial (secondEntry secondPosition.succ)).symm)
  · -- The concatenation ends at the second witness's final position.
    change second.targetRight = final
      (entries (Fin.natAdd (firstUses + 1) (Fin.last secondUses)))
    exact second.end_eq.trans (congrArg final (secondEntry (Fin.last secondUses))).symm

/-- Concatenation adds each assumption's number of uses.

Banfi, Section 2.3.1 (printed p. 14), counts
"`tⱼ := |{k | iₖ = j, k ∈ [n]}|`". Splitting the disjoint position ranges
therefore adds their cardinalities, even when both chains use the same premise. -/
theorem usageCount_append [DecidableEq ι] {target : C} {firstUses secondUses : Nat}
    (first : Implication boundary systems target firstUses)
    (second : Implication boundary systems target secondUses)
    (join : first.targetRight = second.targetLeft) (assumption : ι) :
    (first.append second join).usageCount assumption =
      first.usageCount assumption + second.usageCount assumption := by
  -- Replace cardinalities by indicators and split the concatenated position range.
  unfold usageCount
  simp only [Finset.card_eq_sum_ones, Finset.sum_filter]
  refine (Fin.sum_univ_add (a := firstUses + 1) (b := secondUses + 1)
    (fun position => if (first.append second join).index position = assumption
      then (1 : Nat) else 0)).trans ?_
  simp only [append, Fin.addCases_left, Fin.addCases_right]

end Implication

/-- Implication generated by the named assumptions, with use counts erased
only from the proposition, not from its witnessing finite chain.

Banfi, Section 2.3.1 (printed p. 15): "making the values `t₁, ..., tₙ`
implicit". Exact endpoint equations identify the requested systems with the
two endpoints stored in the witness. -/
def derivable (boundary : ι → C)
    (systems : ∀ i, Bool → Phi (boundary i))
    {target : C} (left right : Phi target) : Prop :=
  ∃ uses, ∃ implication : Implication boundary systems target uses,
    implication.targetLeft = left ∧ implication.targetRight = right

/-- The relation generated by finite chains satisfies the substitution laws.

Banfi, Definition 2.3.1 (printed p. 13): "Symmetry", "Transitivity", and
"Preservation". These are proved here by transforming explicit witnesses,
not assumed of an otherwise unspecified relation. No reflexivity or
single-use closure is asserted. -/
def generatedRelation (boundary : ι → C)
    (systems : ∀ i, Bool → Phi (boundary i)) : SubstitutionRelation C where
  substitutes := fun _ => derivable boundary systems
  symmetric := fun _ => ⟨by
    rintro left right ⟨uses, implication, leftEq, rightEq⟩
    -- Reverse the positions and direction bits, retaining the same counts.
    exact ⟨uses, implication.reverse, rightEq, leftEq⟩⟩
  transitive := fun _ => ⟨by
    rintro left middle right ⟨firstUses, first, firstLeft, firstRight⟩
      ⟨secondUses, second, secondLeft, secondRight⟩
    -- The named middle system supplies the exact boundary join.
    exact ⟨(firstUses + 1) + secondUses,
      first.append second (firstRight.trans secondLeft.symm), firstLeft, secondRight⟩⟩
  preserved := fun converter => by
    rintro left right ⟨uses, implication, leftEq, rightEq⟩
    -- Compose the outer converter with every transformation of the chain.
    exact ⟨uses, implication.map converter,
      congrArg (attach converter) leftEq,
      congrArg (attach converter) rightEq⟩

/-- Every generated implication is valid in any selected substitution
semantics satisfying the named premises.

Banfi, Lemma 2.3.2 (printed p. 16): "then `ρ₁(S₁) ≃ ρₙ(Tₙ)`".
The explicit assumption indices and direction bits of Section 2.3.1
(printed p. 15) select each premise used by this interpretation. -/
theorem derivable_substitutes (relation : SubstitutionRelation C)
    (premise : ∀ i,
      relation.substitutes (boundary i) (systems i false) (systems i true))
    {target : C} {left right : Phi target}
    (derived : derivable boundary systems left right) :
    relation.substitutes target left right := by
  obtain ⟨uses, implication, leftEq, rightEq⟩ := derived
  -- Interpret the same explicit chain using the supplied premise semantics.
  have valid := implication.substitutes relation premise
  -- Exact endpoint equations recover the requested systems.
  rw [leftEq, rightEq] at valid
  exact valid

end ConstructiveCryptography.CryptographicAlgebra.SubstitutionRelation
